### ISSUE TITLE
SNS utils doesn't like an empty subject

### ISSUE THREAD

**Issue by alexwlchan** [wellcometrust/platform#1107]
```
An error occurred (InvalidParameter) when calling the Publish operation: Invalid parameter: Subject: InvalidParameterException
Traceback (most recent call last):
File "/var/task/xml_to_json_run_task.py", line 56, in main
cmd
File "/var/task/wellcome_lambda_utils/sns_utils.py", line 36, in publish_sns_message
Subject=subject
File "/var/task/botocore/client.py", line 253, in _api_call
return self._make_api_call(operation_name, kwargs)
File "/var/task/botocore/client.py", line 557, in _make_api_call
raise error_class(parsed_response, operation_name)
botocore.errorfactory.InvalidParameterException: An error occurred (InvalidParameter) when calling the Publish operation: Invalid parameter: Subject
```

**Comment by alexwlchan** [comment]
Fixed by @alicefuzier
