### ISSUE TITLE
500 when trying to retrieve L0009709

### ISSUE THREAD

**Issue by alexwlchan** [wellcometrust/platform#1148]
A handful of derivatives from this image are returning 500 errors. For example:

https://iiif-origin.wellcomecollection.org/image/s3:L0009000/L0009709.jpg/full/180,/0/default.jpg
https://iiif-origin.wellcomecollection.org/image/s3:L0009000/L0009709.jpg/full/282,/0/default.jpg

Weirdly, it doesn’t seem to affect the full-sized image:

https://iiif-origin.wellcomecollection.org/image/s3:L0009000/L0009709.jpg/full/full/0/default.jpg

The answer here is probably to delete the cache file, but we should think about whether Loris could be smarter here, and delete it for us.

**Comment by alexwlchan** [comment]
So it turns out there are two bugs here:

* Our JPEG derivative for L0009709.jpg is corrupted. Comparing the JP2 and the JPEG derivative side-by-side, we see the bottom of the JPEG is incomplete. (The JPEG I have matches the MD5 for the derivatives in our Loris caches.)

    ![screen shot 2017-11-07 at 09 55 10](https://user-images.githubusercontent.com/301220/32487523-cee27a94-c3a1-11e7-9a79-3df4caf98c42.png)

* Pillow in Loris isn’t configure to handle truncated images correctly. The following program reproduces the error:

    ```python
    from PIL import Image

    im = Image.open('L0009709.jpg')
    im.resize([282, 384])
    ```

    ```
    Traceback (most recent call last):
      File "./example.py", line 8, in <module>
        im.resize([282, 384])
      File "/Users/chana/.virtualenvs/loris-dev/lib/python2.7/site-packages/PIL/Image.py", line 1630, in resize
        self.load()
      File "/Users/chana/.virtualenvs/loris-dev/lib/python2.7/site-packages/PIL/ImageFile.py", line 231, in load
        "(%d bytes not processed)" % len(b))
    IOError: image file is truncated (10 bytes not processed)
    ```

So a fix is in three parts:

* [ ] Fix the JPEG derivative, and flush the old one from our cache
* [ ] Do a local Loris patch to allow truncated images (`from PIL import ImageFile; ImageFile.LOAD_TRUNCATED_IMAGES = True`)
* [ ] Propose the same fix upstream

**Comment by alexwlchan** [comment]
I cut a new JPEG derivative locally, and uploaded it directly to the Loris bucket. Closing, because these requests work now. \o/
