### ISSUE TITLE
ConditionalCheckFailedException in sierra_items_to_dynamo spams the logs with a traceback

### ISSUE THREAD

**Issue by alexwlchan** [wellcometrust/platform#1452]
An example from the weekend:

```
com.amazonaws.services.dynamodbv2.model.ConditionalCheckFailedException: The conditional request failed (Service: AmazonDynamoDBv2; Status Code: 400; Error Code: ConditionalCheckFailedException; Request ID: E70MMST0JSSCU0IP6ES36HTKR3VV4KQNSO5AEMVJF66Q9ASUAAJG)
at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleErrorResponse(AmazonHttpClient.java:1639)
at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1304)
at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1056)
at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:717)
at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:699)
at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:667)
at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:649)
at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:513)
at com.amazonaws.services.dynamodbv2.AmazonDynamoDBClient.putItem(AmazonDynamoDBClient.java:1442)
at com.amazonaws.services.dynamodbv2.AmazonDynamoDBClient.invoke(AmazonDynamoDBClient.java:2162)
at com.amazonaws.services.dynamodbv2.AmazonDynamoDBClient.executePutItem(AmazonDynamoDBClient.java:1466)
at com.amazonaws.services.dynamodbv2.AmazonDynamoDBClient.doInvoke(AmazonDynamoDBClient.java:2186)
at com.gu.scanamo.ops.ScanamoInterpreters$$anon$1$$anonfun$apply$4.apply(ScanamoInterpreters.scala:36)
at com.gu.scanamo.ops.ScanamoInterpreters$$anon$1$$anonfun$apply$4.apply(ScanamoInterpreters.scala:36)
at cats.syntax.EitherSyntax$CatchOnlyPartiallyApplied$.apply$extension(either.scala:29)
at com.gu.scanamo.ops.ScanamoInterpreters$$anon$1.apply(ScanamoInterpreters.scala:35)
at com.gu.scanamo.ops.ScanamoInterpreters$$anon$1.apply(ScanamoInterpreters.scala:30)
at cats.free.Free$$anonfun$foldMap$1.apply(Free.scala:155)
at cats.free.Free$$anonfun$foldMap$1.apply(Free.scala:153)
at cats.package$$anon$1.tailRecM(package.scala:42)
at cats.free.Free.foldMap(Free.scala:153)
at com.gu.scanamo.Scanamo$.exec(Scanamo.scala:17)
```

Since this is an entirely expected exception, we should be suppressing the traceback and print our own log. Cleans up the logs, makes it easier to distinguish legitimate errors (of which we still have a few to hunt down!).

**Comment by alexwlchan** [comment]
Also, this error message in SQSWorkerToDynamo could be _way_ more specific:

```scala
case e: ConditionalCheckFailedException =>
  logger.warn(s"Failed processing $message", e)
  throw GracefulFailureException(e)
```

**Comment by alexwlchan** [comment]
Closing for now; tracebacks are less of an issue and that log message has been improved.
