### ISSUE TITLE
MARC records from Sierra are too large for SNS

### ISSUE THREAD

**Issue by alexwlchan** [wellcometrust/platform#1460]
```
An error occurred (InvalidParameter) when calling the Publish operation: Invalid parameter: Message too long: InvalidParameterException
Traceback (most recent call last):
 File "/var/task/dynamo_to_sns.py", line 56, in main
   message=message
 File "/var/task/wellcome_aws_utils/sns_utils.py", line 45, in publish_sns_message
   Subject=subject
 File "/var/task/botocore/client.py", line 317, in _api_call
   return self._make_api_call(operation_name, kwargs)
 File "/var/task/botocore/client.py", line 615, in _make_api_call
   raise error_class(parsed_response, operation_name)
botocore.errorfactory.InvalidParameterException: An error occurred (InvalidParameter) when calling the Publish operation: Invalid parameter: Message too long
```

http://amzn.to/2DxEoDX / http://amzn.to/2E5Mcxx

**Comment by alexwlchan** [comment]
Being handled in #1470.
