### ISSUE TITLE
Null pointer error thrown by the API

### ISSUE THREAD

**Issue by alexwlchan** [wellcometrust/platform#1482]
If you look at the Sierra index in the API (staging or prod), you get a null pointer error from ~something in Elasticsearch:

```
ERROR u.a.w.p.a.f.e.GeneralExceptionMapper - Sending HTTP 500 from GeneralExceptionMapper
java.lang.NullPointerException: null
  at uk.ac.wellcome.platform.api.models.DisplayLicense$.apply(DisplayLicense.scala:31)
  at uk.ac.wellcome.platform.api.models.DisplayLocation$.apply(DisplayLocation.scala:38)
  at uk.ac.wellcome.platform.api.models.DisplayItem$$anonfun$apply$2.apply(DisplayItem.scala:47)
  at uk.ac.wellcome.platform.api.models.DisplayItem$$anonfun$apply$2.apply(DisplayItem.scala:47)
  at scala.collection.immutable.List.map(List.scala:284)
  at uk.ac.wellcome.platform.api.models.DisplayItem$.apply(DisplayItem.scala:47)
  at uk.ac.wellcome.platform.api.models.DisplayWork$$anonfun$6.apply(DisplayWork.scala:96)
  at uk.ac.wellcome.platform.api.models.DisplayWork$$anonfun$6.apply(DisplayWork.scala:96)
  at scala.collection.immutable.List.map(List.scala:284)
  at uk.ac.wellcome.platform.api.models.DisplayWork$.apply(DisplayWork.scala:96)
  at uk.ac.wellcome.platform.api.models.DisplayWork$.jsonToDisplayWork(DisplayWork.scala:115)
  at uk.ac.wellcome.platform.api.models.DisplayWork$.apply(DisplayWork.scala:106)
  at uk.ac.wellcome.platform.api.models.DisplayResultList$$anonfun$1.apply(DisplayResultList.scala:26)
  at uk.ac.wellcome.platform.api.models.DisplayResultList$$anonfun$1.apply(DisplayResultList.scala:26)
  at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
  at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
  at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
  at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:186)
  at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
  at scala.collection.mutable.ArrayOps$ofRef.map(ArrayOps.scala:186)
  at uk.ac.wellcome.platform.api.models.DisplayResultList$.apply(DisplayResultList.scala:26)
  at uk.ac.wellcome.platform.api.services.WorksService$$anonfun$listWorks$1.apply(WorksService.scala:40)
  at uk.ac.wellcome.platform.api.services.WorksService$$anonfun$listWorks$1.apply(WorksService.scala:40)
  at scala.util.Success$$anonfun$map$1.apply(Try.scala:237)
  at scala.util.Try$.apply(Try.scala:192)
  at scala.util.Success.map(Try.scala:237)
  at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:237)
  at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:237)
  at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:36)
  at scala.concurrent.impl.ExecutionContextImpl$AdaptedForkJoinTask.exec(ExecutionContextImpl.scala:121)
  at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
  at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
  at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
  at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
INFO c.t.f.h.filters.AccessLoggingFilter - 172.17.0.3 - - [27/Jan/2018:20:20:57 +0000] "GET /catalogue/v1/works?_index=sierra-bibs-title&includes=identifiers,items HTTP/1.0" 500 158 26 "Mozilla/5.0 (Linux; Android 8.1.0; Pixel XL Build/OPM1.171019.012) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.123 Mobile Safari/537.36"
```

**Comment by alexwlchan** [comment]
So some of these are being thrown in the prod API because of missing titles (on works with visible=false), and now I can't find an error in the staging API???

Closing for now.
