### ISSUE TITLE
Log spam in sierra_reader tests (and probably others)

### ISSUE THREAD

**Issue by alexwlchan** [wellcometrust/platform#1644]
For example https://travis-ci.org/wellcometrust/platform/jobs/350423421#L2366

```
17:45:38.784 [ForkJoinPool-2-worker-43] ERROR uk.ac.wellcome.sqs.SQSReader - Error retrieving messages from queue 
com.amazonaws.SdkClientException: Unable to load AWS credentials from any provider in the chain
	at com.amazonaws.auth.AWSCredentialsProviderChain.getCredentials(AWSCredentialsProviderChain.java:131)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.getCredentialsFromContext(AmazonHttpClient.java:1164)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.runBeforeRequestHandlers(AmazonHttpClient.java:762)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:724)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:717)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:699)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:667)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:649)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:513)
	at com.amazonaws.services.sqs.AmazonSQSClient.doInvoke(AmazonSQSClient.java:1689)
	at com.amazonaws.services.sqs.AmazonSQSClient.invoke(AmazonSQSClient.java:1665)
	at com.amazonaws.services.sqs.AmazonSQSClient.receiveMessage(AmazonSQSClient.java:1295)
	at uk.ac.wellcome.sqs.SQSReader.uk$ac$wellcome$sqs$SQSReader$$receiveMessages(SQSReader.scala:53)
	at uk.ac.wellcome.sqs.SQSReader$$anonfun$retrieveAndDeleteMessages$2$$anonfun$apply$2.apply(SQSReader.scala:31)
	at uk.ac.wellcome.sqs.SQSReader$$anonfun$retrieveAndDeleteMessages$2$$anonfun$apply$2.apply(SQSReader.scala:29)
	at scala.concurrent.BlockContext$DefaultBlockContext$.blockOn(BlockContext.scala:53)
	at scala.concurrent.package$.blocking(package.scala:123)
	at uk.ac.wellcome.sqs.SQSReader$$anonfun$retrieveAndDeleteMessages$2.apply(SQSReader.scala:29)
	at uk.ac.wellcome.sqs.SQSReader$$anonfun$retrieveAndDeleteMessages$2.apply(SQSReader.scala:29)
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24)
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24)
	at scala.concurrent.impl.ExecutionContextImpl$AdaptedForkJoinTask.exec(ExecutionContextImpl.scala:121)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)

```

**Comment by alexwlchan** [comment]
My suspicion is that we just aren't passing the right flags in the server tests. Should be a cheap win; I'll pick this up tomorrow.
