### ISSUE TITLE
ID minter is failing to connect to RDS on startup

### ISSUE THREAD

**Issue by alexwlchan** [wellcometrust/platform#1684]
From the logs:

```
at org.flywaydb.core.internal.util.jdbc.JdbcUtils.openConnection(JdbcUtils.java:51)
org.flywaydb.core.internal.dbsupport.FlywaySqlException:
Unable to obtain Jdbc connection from DataSource (jdbc:mysql://identifiers.cluster-<cluster_id>.eu-west-1.rds.amazonaws.com:3306/identifiers) for user 'wellcome': Too many connections
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
SQL State : 08004
Error Code : 1040
Message : Too many connections
at org.flywaydb.core.internal.util.jdbc.DriverDataSource.getConnectionFromDriver(DriverDataSource.java:419)
at org.flywaydb.core.internal.util.jdbc.DriverDataSource.getConnection(DriverDataSource.java:381)
09:15:28.893 [main] ERROR c.t.i.app.internal.InstalledModules - Startup method error in uk.ac.wellcome.platform.idminter.modules.IdMinterWorkerModule$@5c1f6d57
at org.flywaydb.core.Flyway.execute(Flyway.java:1418)
at org.flywaydb.core.Flyway.migrate(Flyway.java:971)
at uk.ac.wellcome.platform.idminter.database.TableProvisioner.provision(TableProvisioner.scala:22)
at uk.ac.wellcome.platform.idminter.modules.IdMinterWorkerModule$.singletonStartup(IdMinterWorkerModule.scala:21)
at com.twitter.inject.app.internal.InstalledModules$$anonfun$postInjectorStartup$1.apply(InstalledModules.scala:81)
at com.twitter.inject.app.internal.InstalledModules$$anonfun$postInjectorStartup$1.apply(InstalledModules.scala:78)
at scala.collection.immutable.List.foreach(List.scala:392)
at com.twitter.inject.app.internal.InstalledModules.postInjectorStartup(InstalledModules.scala:78)
at com.twitter.inject.app.App$class.main(App.scala:57)
at uk.ac.wellcome.platform.idminter.Server.com$twitter$inject$server$TwitterServer$$super$main(Server.scala:17)
at com.twitter.inject.server.TwitterServer$class.main(TwitterServer.scala:128)
at uk.ac.wellcome.platform.idminter.Server.main(Server.scala:17)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at com.twitter.inject.app.internal.InstalledModules$$anonfun$postInjectorStartup$1.apply(InstalledModules.scala:81)
at com.twitter.app.App$$anonfun$nonExitingMain$3.apply(App.scala:176)
at com.twitter.app.App$$anonfun$nonExitingMain$3.apply(App.scala:175)
at scala.Option.foreach(Option.scala:257)
at com.twitter.app.App$class.nonExitingMain(App.scala:175)
at uk.ac.wellcome.platform.idminter.Server.nonExitingMain(Server.scala:17)
at com.twitter.app.App$class.main(App.scala:141)
at uk.ac.wellcome.platform.idminter.Server.main(Server.scala:17)
at uk.ac.wellcome.platform.idminter.ServerMain.main(Server.scala)
Caused by: java.sql.SQLNonTransientConnectionException: Too many connections
at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:526)
at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:513)
at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:115)
at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:1606)
at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:633)
at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:347)
at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:219)
at org.flywaydb.core.internal.util.jdbc.DriverDataSource.getConnectionFromDriver(DriverDataSource.java:416)
... 26 common frames omitted
```

This error causes the ID minter to fail on startup… get restarted by ECS… and immediately hammer the database for another connection.

Judging by the frequency of new log streams, this has been happening for at least a day.

I think this is blocking us from minting any new IDs. 😱

**Comment by alexwlchan** [comment]
I rebooted both of our RDS instances, which presumably invalidates any existing connections, and should allow the ID minter to reconnect? \*crosses fingers*

**Comment by alexwlchan** [comment]
Reducing the number of running ID minter instances seems to have fixed things. We may want to revisit this if we need more ID minter bandwidth, but this seems to have fixed things for now.
