### ISSUE TITLE
Error – nonexistent queue – in the Sierra bib reader???

### ISSUE THREAD

**Issue by alexwlchan** [wellcometrust/platform#1704]
Spotted while following logs today:

```
ERROR uk.ac.wellcome.sqs.SQSReader - Error processing messages from queue https://sqs.eu-west-1.amazonaws.com/760097843905/sierra_bibs_windows
com.amazonaws.services.sqs.model.QueueDoesNotExistException: The specified queue does not exist for this wsdl version. (Service: AmazonSQS; Status Code: 400; Error Code: AWS.SimpleQueueService.NonExistentQueue; Request ID: 08540843-91d0-52de-a4e1-5b697bcfeb84)
at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleErrorResponse(AmazonHttpClient.java:1639)
at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1304)
at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1056)
at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:743)
at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:717)
at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:699)
at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:667)
at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:649)
at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:513)
at com.amazonaws.services.sqs.AmazonSQSClient.doInvoke(AmazonSQSClient.java:1689)
at com.amazonaws.services.sqs.AmazonSQSClient.invoke(AmazonSQSClient.java:1665)
at com.amazonaws.services.sqs.AmazonSQSClient.deleteMessage(AmazonSQSClient.java:762)
at uk.ac.wellcome.sqs.SQSReader$$anonfun$uk$ac$wellcome$sqs$SQSReader$$deleteMessage$1$$anonfun$apply$mcV$sp$1.apply$mcV$sp(SQSReader.scala:96)
at uk.ac.wellcome.sqs.SQSReader$$anonfun$uk$ac$wellcome$sqs$SQSReader$$deleteMessage$1$$anonfun$apply$mcV$sp$1.apply(SQSReader.scala:92)
at uk.ac.wellcome.sqs.SQSReader$$anonfun$uk$ac$wellcome$sqs$SQSReader$$deleteMessage$1$$anonfun$apply$mcV$sp$1.apply(SQSReader.scala:92)
at scala.concurrent.BlockContext$DefaultBlockContext$.blockOn(BlockContext.scala:53)
at scala.concurrent.package$.blocking(package.scala:123)
at uk.ac.wellcome.sqs.SQSReader$$anonfun$uk$ac$wellcome$sqs$SQSReader$$deleteMessage$1.apply(SQSReader.scala:92)
at uk.ac.wellcome.sqs.SQSReader$$anonfun$uk$ac$wellcome$sqs$SQSReader$$deleteMessage$1.apply(SQSReader.scala:92)
at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24)
at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24)
at scala.concurrent.impl.ExecutionContextImpl$AdaptedForkJoinTask.exec(ExecutionContextImpl.scala:121)
at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
```

**Comment by alexwlchan** [comment]
We haven’t seen this for a while, so closing.
