### ISSUE TITLE
Flaky/broken Elasticsearch test in master

### ISSUE THREAD

**Issue by alexwlchan** [wellcometrust/platform#1747]
The following test is either flaky or broken in ElasticSearchIndexTest.scala:

```scala
  it("create an index where inserting a doc of an unexpected type fails") {
    withLocalElasticsearchIndex(TestIndex) { indexName =>
      val badTestObject = BadTestObject("id", 5)
      val badTestObjectJson = JsonUtil.toJson(badTestObject).get

      val eventuallyResponse =
        for {
          response <- elasticClient.execute(
            indexInto(indexName / testType).doc(badTestObjectJson))
        } yield response

      whenReady(eventuallyResponse.failed) { exception =>
        exception shouldBe a[ResponseException]
      }      
    }
  }
```

It failed in the last two builds on master; I haven’t restarted the builds yet. Here’s the error:

```
[info] - create an index where inserting a doc of an unexpected type fails *** FAILED ***
[info]   org.elasticsearch.client.ResponseException: PUT http://localhost:9200/test_index/_mapping/thing: HTTP/1.1 404 Not Found
[info] {"error":{"root_cause":[{"type":"index_not_found_exception","reason":"no such index","index_uuid":"KoLMQLMuRQO9CV0tMVLyLA","index":"test_index"}],"type":"index_not_found_exception","reason":"no such index","index_uuid":"KoLMQLMuRQO9CV0tMVLyLA","index":"test_index"},"status":404}
[info]   at org.elasticsearch.client.RestClient$1.completed(RestClient.java:354)
[info]   at org.elasticsearch.client.RestClient$1.completed(RestClient.java:343)
[info]   at org.apache.http.concurrent.BasicFuture.completed(BasicFuture.java:119)
[info]   at org.apache.http.impl.nio.client.DefaultClientExchangeHandlerImpl.responseCompleted(DefaultClientExchangeHandlerImpl.java:177)
[info]   at org.apache.http.nio.protocol.HttpAsyncRequestExecutor.processResponse(HttpAsyncRequestExecutor.java:436)
[info]   at org.apache.http.nio.protocol.HttpAsyncRequestExecutor.inputReady(HttpAsyncRequestExecutor.java:326)
[info]   at org.apache.http.impl.nio.DefaultNHttpClientConnection.consumeInput(DefaultNHttpClientConnection.java:265)
[info]   at org.apache.http.impl.nio.client.InternalIODispatch.onInputReady(InternalIODispatch.java:81)
[info]   at org.apache.http.impl.nio.client.InternalIODispatch.onInputReady(InternalIODispatch.java:39)
[info]   at org.apache.http.impl.nio.reactor.AbstractIODispatch.inputReady(AbstractIODispatch.java:114)
[info]   ...
```

Thing is, I’m not sure what this test is actually testing, but maybe somebody else can enlighten me?

And weirdly, it passes locally.

**Comment by kenoir** [comment]
Closing as out of date.
