### ISSUE TITLE
Flakiness in the storage-tests

### ISSUE THREAD

**Issue by alexwlchan** [wellcometrust/platform#2139]
@alicefuzier and I have both seen this; a log is attached. It looks like the S3 container we use for tests is failing to respond in a timely fashion, but it was [last pushed four months ago](https://hub.docker.com/r/scality/s3server/) so I don’t think it’s changed silently?

[log.txt](https://github.com/wellcometrust/platform/files/2039857/log.txt)

**Comment by alexwlchan** [comment]
One slightly unusual thing about the storage stack is that it uses a v3 docker-compose.yml, where most of our stacks are stuck on v2. I’ve switched to a consistent version throughout (753b893), and maybe that will give us the mysterious timing fix we want?

**Comment by alicefuzier** [comment]
Storage flakiness in #2167 too

**Comment by alexwlchan** [comment]
Well bang goes that theory.

**Comment by alicefuzier** [comment]
And master https://travis-ci.org/wellcometrust/platform/jobs/386587333
```
[info] StringStoreVersionedHybridStoreTest:
[info] with S3StringStore
[info] - stores a record if it has never been seen before *** FAILED ***
[info]   com.amazonaws.SdkClientException: Unable to execute HTTP request: The target server failed to respond
[info]   at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleRetryableException(AmazonHttpClient.java:1114)
[info]   at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1064)
[info]   at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:743)
[info]   at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:717)
[info]   at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:699)
[info]   at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:667)
[info]   at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:649)
[info]   at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:513)
[info]   at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4247)
[info]   at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4194)
[info]   ...
[info]   Cause: org.apache.http.NoHttpResponseException: The target server failed to respond
[info]   at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:143)
[info]   at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:57)
[info]   at org.apache.http.impl.io.AbstractMessageParser.parse(AbstractMessageParser.java:261)
[info]   at org.apache.http.impl.DefaultBHttpClientConnection.receiveResponseHeader(DefaultBHttpClientConnection.java:165)
[info]   at org.apache.http.impl.conn.CPoolProxy.receiveResponseHeader(CPoolProxy.java:167)
[info]   at org.apache.http.protocol.HttpRequestExecutor.doReceiveResponse(HttpRequestExecutor.java:272)
[info]   at com.amazonaws.http.protocol.SdkHttpRequestExecutor.doReceiveResponse(SdkHttpRequestExecutor.java:82)
[info]   at org.apache.http.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:124)
[info]   at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:271)
[info]   at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:184)
[info]   ...
```

**Comment by alexwlchan** [comment]
And in #2173.

[log-2.txt](https://github.com/wellcometrust/platform/files/2063097/log-2.txt)

**Comment by alexwlchan** [comment]
We seem to have squashed this, yay!
