### ISSUE TITLE
Reduce our CloudWatch costs

### ISSUE THREAD

**Issue by alexwlchan** [wellcometrust/platform#2177]
We spent a bit much on CloudWatch last month; it would be nice to make these numbers more sensible. This is a tracking ticket for ways to reduce our bills:

- [x] Only log the Lambda event when we have an error: https://github.com/wellcometrust/aws_utils/pull/18
- [x] Only log SNS responses in Lambdas when we have an error: https://github.com/wellcometrust/aws_utils/pull/19
- [x] Don’t log an enormous stack trace for ConditionalCheckFailed exceptions:

    ```
    java.lang.RuntimeException: ConditionNotMet(com.amazonaws.services.dynamodbv2.model.ConditionalCheckFailedException: The conditional request failed (Service: AmazonDynamoDBv2; Status Code: 400; Error Code: ConditionalCheckFailedException; Request ID: 0FEMQRMOTFA1F4BV2G021JS9V7VV4KQNSO5AEMVJF66Q9ASUAAJG))
        at uk.ac.wellcome.storage.dynamo.VersionedDao.$anonfun$updateRecord$3(VersionedDao.scala:65)
        at uk.ac.wellcome.storage.dynamo.VersionedDao.$anonfun$updateRecord$3$adapted(VersionedDao.scala:62)
        at scala.Option.map(Option.scala:146)
        at uk.ac.wellcome.storage.dynamo.VersionedDao.$anonfun$updateRecord$1(VersionedDao.scala:62)
        at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
        at scala.concurrent.Future$.$anonfun$apply$1(Future.scala:654)
        at scala.util.Success.$anonfun$map$1(Try.scala:251)
    00:13:32.118 [ForkJoinPool-4-worker-14] WARN  u.a.w.storage.dynamo.VersionedDao - Failed to updating Dynamo record: sierra/1832158
        at scala.concurrent.Future.$anonfun$map$1(Future.scala:288)
        at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:29)
        at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:29)
        at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:60)
        at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402)
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
        at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)```
    ```

- [x] Ditto ProvisionedThroughputExceeded:

    ```
    com.amazonaws.services.dynamodbv2.model.ProvisionedThroughputExceededException: The level of configured provisioned throughput for one or more global secondary indexes of the table was exceeded. Consider increasing your provisioning level for the under-provisioned global secondary indexes with the UpdateTable API (Service: AmazonDynamoDBv2; Status Code: 400; Error Code: ProvisionedThroughputExceededException; Request ID: 04Q459L2R2GU6K5ORR154DUIJVVV4KQNSO5AEMVJF66Q9ASUAAJG)
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleErrorResponse(AmazonHttpClient.java:1639)
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1304)
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1056)
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:743)
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:717)
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:699)
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:667)
        at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:649)
        at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:513)
        at com.amazonaws.services.dynamodbv2.AmazonDynamoDBClient.doInvoke(AmazonDynamoDBClient.java:2186)
        at com.amazonaws.services.dynamodbv2.AmazonDynamoDBClient.invoke(AmazonDynamoDBClient.java:2162)
        at com.amazonaws.services.dynamodbv2.AmazonDynamoDBClient.executeUpdateItem(AmazonDynamoDBClient.java:1908)
        at com.amazonaws.services.dynamodbv2.AmazonDynamoDBClient.updateItem(AmazonDynamoDBClient.java:1884)
        at com.gu.scanamo.ops.ScanamoInterpreters$$anon$1.$anonfun$apply$3(ScanamoInterpreters.scala:58)
        at cats.syntax.EitherSyntax$CatchOnlyPartiallyApplied$.apply$extension(either.scala:29)
        at com.gu.scanamo.ops.ScanamoInterpreters$$anon$1.apply(ScanamoInterpreters.scala:57)
        at com.gu.scanamo.ops.ScanamoInterpreters$$anon$1.apply(ScanamoInterpreters.scala:30)
        at cats.free.Free.$anonfun$foldMap$1(Free.scala:155)
        at cats.package$$anon$1.tailRecM(package.scala:42)
        at cats.free.Free.foldMap(Free.scala:153)
        at cats.free.Free.$anonfun$foldMap$1(Free.scala:156)
        at cats.package$$anon$1.tailRecM(package.scala:42)
        at cats.free.Free.foldMap(Free.scala:153)
        at com.gu.scanamo.Scanamo$.exec(Scanamo.scala:17)
        at uk.ac.wellcome.storage.dynamo.VersionedDao.$anonfun$updateRecord$3(VersionedDao.scala:63)
        at uk.ac.wellcome.storage.dynamo.VersionedDao.$anonfun$updateRecord$3$adapted(VersionedDao.scala:62)
    01:08:46.153 [ForkJoinPool-2-worker-35] ERROR u.a.wellcome.messaging.sqs.SQSReader - Error processing messages from queue https://sqs.eu-west-1.amazonaws.com/760097843905/sierra_bibs_merger_queue
        at uk.ac.wellcome.storage.dynamo.VersionedDao.$anonfun$updateRecord$1(VersionedDao.scala:62)
        at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
        at scala.concurrent.Future$.$anonfun$apply$1(Future.scala:654)
        at scala.util.Success.$anonfun$map$1(Try.scala:251)
        at scala.util.Success.map(Try.scala:209)
        at scala.concurrent.Future.$anonfun$map$1(Future.scala:288)
        at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:29)
        at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:29)
        at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:60)
        at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402)
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
        at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
    ```

- [x] And massive GracefulFailureException tracebacks

        08:19:15.077 [default-akka.actor.default-dispatcher-6] WARN  u.a.wellcome.messaging.sqs.SQSStream - Graceful failure processing message 4d9c5a2a-16bf-4f5e-977a-5185b752c844
        uk.ac.wellcome.exceptions.GracefulFailureException: expected json value got < (line 1, column 1)
        	at uk.ac.wellcome.utils.JsonUtil$$anonfun$fromJson$1.applyOrElse(JsonUtil.scala:38)
        	at uk.ac.wellcome.utils.JsonUtil$$anonfun$fromJson$1.applyOrElse(JsonUtil.scala:35)
        	at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:34)
        	at scala.util.Failure.recover(Try.scala:230)
        	at uk.ac.wellcome.utils.JsonUtil$.fromJson(JsonUtil.scala:35)
        	at uk.ac.wellcome.platform.reindex_worker.services.ReindexWorkerService.processMessage(ReindexWorkerService.scala:28)
        	at uk.ac.wellcome.platform.reindex_worker.services.ReindexWorkerService.$anonfun$new$1(ReindexWorkerService.scala:24)
        	at uk.ac.wellcome.messaging.sqs.SQSStream.$anonfun$readAndProcess$2(SQSStream.scala:58)
        	at scala.concurrent.Future.$anonfun$flatMap$1(Future.scala:303)
        	at scala.concurrent.impl.Promise.$anonfun$transformWith$1(Promise.scala:37)
        	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:60)
        	at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:55)
        	at akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:91)
        	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
        	at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:81)
        	at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:91)
        	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:40)
        	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:43)
        	at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
        	at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
        	at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
        	at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
- [ ] Fix this warning. It’s spammy and probably telling us something useful!

      WARN  c.a.services.s3.AmazonS3Client No content length specified for stream data.  Stream contents will be buffered in memory and could result in out of memory errors.

**Comment by alexwlchan** [comment]
Oh jeez.

```
06:21:05.179 [pool-5-thread-1-ScalaTest-running-IdentifiersDaoTest] WARN  u.a.w.p.i.database.IdentifiersDao - Unable to insert Identifier(Sweeteners and sugar cane,Cropssss,The microscopic world of eyelash lice,Sunflower seeds in a sack) because of integrity constraints
java.sql.SQLIntegrityConstraintViolationException: Duplicate entry 'Cropssss-The microscopic world of eyelash lice-Sunflower seeds i' for key 'UniqueFromSource'
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:533)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:513)
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:115)
	at com.mysql.cj.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:1983)
	at com.mysql.cj.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1826)
	at com.mysql.cj.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2034)
	at com.mysql.cj.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:1970)
	at com.mysql.cj.jdbc.PreparedStatement.executeLargeUpdate(PreparedStatement.java:5001)
	at com.mysql.cj.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1955)
	at org.apache.commons.dbcp2.DelegatingPreparedStatement.executeUpdate(DelegatingPreparedStatement.java:98)
	at org.apache.commons.dbcp2.DelegatingPreparedStatement.executeUpdate(DelegatingPreparedStatement.java:98)
	at scalikejdbc.DBConnectionAttributesWiredPreparedStatement.executeUpdate(DBConnectionAttributesWiredPreparedStatement.scala:79)
	at scalikejdbc.StatementExecutor.$anonfun$executeUpdate$1(StatementExecutor.scala:341)
	at scala.runtime.java8.JFunction0$mcI$sp.apply(JFunction0$mcI$sp.java:12)
	at scalikejdbc.StatementExecutor$NakedExecutor.apply(StatementExecutor.scala:18)
	at scalikejdbc.StatementExecutor$$anon$1.scalikejdbc$StatementExecutor$LoggingSQLAndTiming$$super$apply(StatementExecutor.scala:319)
	at scalikejdbc.StatementExecutor$LoggingSQLAndTiming.apply(StatementExecutor.scala:263)
	at scalikejdbc.StatementExecutor$LoggingSQLAndTiming.apply$(StatementExecutor.scala:249)
	at scalikejdbc.StatementExecutor$$anon$1.scalikejdbc$StatementExecutor$LoggingSQLIfFailed$$super$apply(StatementExecutor.scala:319)
	at scalikejdbc.StatementExecutor$LoggingSQLIfFailed.apply(StatementExecutor.scala:296)
	at scalikejdbc.StatementExecutor$LoggingSQLIfFailed.apply$(StatementExecutor.scala:295)
	at scalikejdbc.StatementExecutor$$anon$1.apply(StatementExecutor.scala:319)
	at scalikejdbc.StatementExecutor.executeUpdate(StatementExecutor.scala:341)
	at scalikejdbc.DBSession.$anonfun$updateWithFilters$1(DBSession.scala:473)
	at scalikejdbc.DBSession.$anonfun$updateWithFilters$1$adapted(DBSession.scala:471)
	at scalikejdbc.LoanPattern.using(LoanPattern.scala:18)
	at scalikejdbc.LoanPattern.using$(LoanPattern.scala:16)
	at scalikejdbc.ActiveSession.using(DBSession.scala:705)
	at scalikejdbc.DBSession.updateWithFilters(DBSession.scala:471)
	at scalikejdbc.DBSession.updateWithFilters$(DBSession.scala:457)
	at scalikejdbc.ActiveSession.updateWithFilters(DBSession.scala:705)
	at scalikejdbc.DBSession.updateWithFilters(DBSession.scala:445)
	at scalikejdbc.DBSession.updateWithFilters$(DBSession.scala:440)
	at scalikejdbc.ActiveSession.updateWithFilters(DBSession.scala:705)
	at scalikejdbc.DBSessionWrapper.$anonfun$updateWithFilters$1(DBSessionWrapper.scala:81)
	at scalikejdbc.DBSessionWrapper.$anonfun$updateWithFilters$1$adapted(DBSessionWrapper.scala:81)
	at scalikejdbc.DBSessionWrapper.$anonfun$withAttributesSwitchedDBSession$1(DBSessionWrapper.scala:35)
	at scalikejdbc.DBSessionAttributesSwitcher.withSwitchedDBSession(DBSessionAttributesSwitcher.scala:31)
	at scalikejdbc.DBSessionWrapper.withAttributesSwitchedDBSession(DBSessionWrapper.scala:34)
	at scalikejdbc.DBSessionWrapper.updateWithFilters(DBSessionWrapper.scala:81)
	at scalikejdbc.SQLUpdate.$anonfun$apply$11(SQL.scala:662)
	at scalikejdbc.SQLUpdate.$anonfun$apply$11$adapted(SQL.scala:662)
	at scalikejdbc.DBConnection.autoCommit(DBConnection.scala:233)
	at scalikejdbc.DBConnection.autoCommit$(DBConnection.scala:231)
	at scalikejdbc.DB.autoCommit(DB.scala:60)
	at scalikejdbc.DB$.$anonfun$autoCommit$1(DB.scala:217)
	at scalikejdbc.LoanPattern.using(LoanPattern.scala:18)
	at scalikejdbc.LoanPattern.using$(LoanPattern.scala:16)
	at scalikejdbc.DB$.using(DB.scala:140)
	at scalikejdbc.DB$.autoCommit(DB.scala:216)
	at scalikejdbc.SQLUpdate.apply(SQL.scala:662)
	at uk.ac.wellcome.platform.idminter.database.IdentifiersDao.$anonfun$saveIdentifier$2(IdentifiersDao.scala:74)
	at scala.runtime.java8.JFunction0$mcI$sp.apply(JFunction0$mcI$sp.java:12)
	at scala.concurrent.BlockContext$DefaultBlockContext$.blockOn(BlockContext.scala:53)
	at scala.concurrent.package$.blocking(package.scala:142)
	at uk.ac.wellcome.platform.idminter.database.IdentifiersDao.$anonfun$saveIdentifier$1(IdentifiersDao.scala:63)
	at scala.runtime.java8.JFunction0$mcI$sp.apply(JFunction0$mcI$sp.java:12)
	at scala.util.Try$.apply(Try.scala:209)
	at uk.ac.wellcome.platform.idminter.database.IdentifiersDao.saveIdentifier(IdentifiersDao.scala:63)
	at uk.ac.wellcome.platform.idminter.database.IdentifiersDaoTest.$anonfun$new$17(IdentifiersDaoTest.scala:208)
	at uk.ac.wellcome.platform.idminter.database.IdentifiersDaoTest.$anonfun$withIdentifiersDao$1(IdentifiersDaoTest.scala:33)
	at uk.ac.wellcome.platform.idminter.fixtures.IdentifiersDatabase.withIdentifiersDatabase(IdentifersDatabase.scala:132)
	at uk.ac.wellcome.platform.idminter.fixtures.IdentifiersDatabase.withIdentifiersDatabase$(IdentifersDatabase.scala:98)
	at uk.ac.wellcome.platform.idminter.database.IdentifiersDaoTest.withIdentifiersDatabase(IdentifiersDaoTest.scala:13)
	at uk.ac.wellcome.platform.idminter.database.IdentifiersDaoTest.withIdentifiersDao(IdentifiersDaoTest.scala:20)
	at uk.ac.wellcome.platform.idminter.database.IdentifiersDaoTest.$anonfun$new$16(IdentifiersDaoTest.scala:191)
	at org.scalatest.OutcomeOf.outcomeOf(OutcomeOf.scala:85)
	at org.scalatest.OutcomeOf.outcomeOf$(OutcomeOf.scala:83)
	at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
	at org.scalatest.Transformer.apply(Transformer.scala:22)
	at org.scalatest.Transformer.apply(Transformer.scala:20)
	at org.scalatest.FunSpecLike$$anon$1.apply(FunSpecLike.scala:454)
	at org.scalatest.TestSuite.withFixture(TestSuite.scala:196)
	at org.scalatest.TestSuite.withFixture$(TestSuite.scala:195)
	at org.scalatest.FunSpec.withFixture(FunSpec.scala:1630)
	at org.scalatest.FunSpecLike.invokeWithFixture$1(FunSpecLike.scala:452)
	at org.scalatest.FunSpecLike.$anonfun$runTest$1(FunSpecLike.scala:464)
	at org.scalatest.SuperEngine.runTestImpl(Engine.scala:289)
	at org.scalatest.FunSpecLike.runTest(FunSpecLike.scala:464)
	at org.scalatest.FunSpecLike.runTest$(FunSpecLike.scala:446)
	at org.scalatest.FunSpec.runTest(FunSpec.scala:1630)
	at org.scalatest.FunSpecLike.$anonfun$runTests$1(FunSpecLike.scala:497)
	at org.scalatest.SuperEngine.$anonfun$runTestsInBranch$1(Engine.scala:396)
	at scala.collection.immutable.List.foreach(List.scala:389)
	at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:384)
	at org.scalatest.SuperEngine.runTestsInBranch(Engine.scala:373)
	at org.scalatest.SuperEngine.$anonfun$runTestsInBranch$1(Engine.scala:410)
	at scala.collection.immutable.List.foreach(List.scala:389)
	at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:384)
	at org.scalatest.SuperEngine.runTestsInBranch(Engine.scala:379)
	at org.scalatest.SuperEngine.runTestsImpl(Engine.scala:461)
	at org.scalatest.FunSpecLike.runTests(FunSpecLike.scala:497)
	at org.scalatest.FunSpecLike.runTests$(FunSpecLike.scala:496)
	at org.scalatest.FunSpec.runTests(FunSpec.scala:1630)
	at org.scalatest.Suite.run(Suite.scala:1147)
	at org.scalatest.Suite.run$(Suite.scala:1129)
	at org.scalatest.FunSpec.org$scalatest$FunSpecLike$$super$run(FunSpec.scala:1630)
	at org.scalatest.FunSpecLike.$anonfun$run$1(FunSpecLike.scala:501)
	at org.scalatest.SuperEngine.runImpl(Engine.scala:521)
	at org.scalatest.FunSpecLike.run(FunSpecLike.scala:501)
	at org.scalatest.FunSpecLike.run$(FunSpecLike.scala:500)
	at org.scalatest.FunSpec.run(FunSpec.scala:1630)
	at org.scalatest.tools.Framework.org$scalatest$tools$Framework$$runSuite(Framework.scala:314)
	at org.scalatest.tools.Framework$ScalaTestTask.execute(Framework.scala:507)
	at sbt.TestRunner.runTest$1(TestFramework.scala:76)
	at sbt.TestRunner.run(TestFramework.scala:85)
	at sbt.TestFramework$$anon$2$$anonfun$$init$$1$$anonfun$apply$8.apply(TestFramework.scala:202)
	at sbt.TestFramework$$anon$2$$anonfun$$init$$1$$anonfun$apply$8.apply(TestFramework.scala:202)
	at sbt.TestFramework$.sbt$TestFramework$$withContextLoader(TestFramework.scala:185)
	at sbt.TestFramework$$anon$2$$anonfun$$init$$1.apply(TestFramework.scala:202)
	at sbt.TestFramework$$anon$2$$anonfun$$init$$1.apply(TestFramework.scala:202)
	at sbt.TestFunction.apply(TestFramework.scala:207)
	at sbt.Tests$.sbt$Tests$$processRunnable$1(Tests.scala:239)
	at sbt.Tests$$anonfun$makeSerial$1.apply(Tests.scala:245)
	at sbt.Tests$$anonfun$makeSerial$1.apply(Tests.scala:245)
	at sbt.std.Transform$$anon$3$$anonfun$apply$2.apply(System.scala:44)
	at sbt.std.Transform$$anon$3$$anonfun$apply$2.apply(System.scala:44)
	at sbt.std.Transform$$anon$4.work(System.scala:63)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
	at sbt.Execute.work(Execute.scala:237)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
	at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by alexwlchan** [comment]
We’re waiting to find out what’s happened to billing this month, and then I think we can close this.

**Comment by kenoir** [comment]
Closing now, the bot will tell us if it worked!
