### ISSUE TITLE
More issues with the Sierra transformer

### ISSUE THREAD

**Issue by alexwlchan** [wellcometrust/platform#2252]
After deploying the latest round of fixes to the transformer, and redriving the transformer DLQ, there are at least two Sierra errors in the logs:

```
uk.ac.wellcome.exceptions.GracefulFailureException: Unrecognised location type: [sgzin]
at uk.ac.wellcome.models.work.internal.LocationType$.apply(LocationType.scala:48)
```

```
uk.ac.wellcome.exceptions.GracefulFailureException: Unrecognised second indicator for production function: [Some(4)]
at uk.ac.wellcome.platform.transformer.transformers.sierra.SierraProduction.$anonfun$getProductionFrom264Fields$1(SierraProduction.scala:128)
```

The first needs more information; the second might be retrievable from the MARC spec for field 264 – but Silver didn’t specify it, should we should check first.

**Comment by alexwlchan** [comment]
Current issues:

```
$ grep 'GracefulFailureException' ~/Desktop/transformer.log  | sort | uniq -c
   8 uk.ac.wellcome.exceptions.GracefulFailureException: Multiple identifiers in subfield $0: List(n2012182555, n79055860)
   8 uk.ac.wellcome.exceptions.GracefulFailureException: Multiple identifiers in subfield $0: List(n2016031324, n86867825)
   8 uk.ac.wellcome.exceptions.GracefulFailureException: Multiple identifiers in subfield $0: List(n2016043477, n85286663)
   8 uk.ac.wellcome.exceptions.GracefulFailureException: Multiple identifiers in subfield $0: List(n2016248258, n82054952)
   8 uk.ac.wellcome.exceptions.GracefulFailureException: Multiple identifiers in subfield $0: List(n2017023999, no97013926)
   8 uk.ac.wellcome.exceptions.GracefulFailureException: Multiple identifiers in subfield $0: List(n50057750, n79055860)
  16 uk.ac.wellcome.exceptions.GracefulFailureException: Multiple identifiers in subfield $0: List(n79091479, n81040096)
  16 uk.ac.wellcome.exceptions.GracefulFailureException: Multiple identifiers in subfield $0: List(n82006560, n95067347)
   8 uk.ac.wellcome.exceptions.GracefulFailureException: Multiple identifiers in subfield $0: List(n83135254, xArtcollections)
   8 uk.ac.wellcome.exceptions.GracefulFailureException: Multiple identifiers in subfield $0: List(n84191703, n97030524)
   8 uk.ac.wellcome.exceptions.GracefulFailureException: Multiple identifiers in subfield $0: List(n94107902, n79036446)
   8 uk.ac.wellcome.exceptions.GracefulFailureException: Multiple identifiers in subfield $0: List(nb2016012115, no89018178)
   8 uk.ac.wellcome.exceptions.GracefulFailureException: Multiple identifiers in subfield $0: List(no2014142978, nb2003084306)
 736 uk.ac.wellcome.exceptions.GracefulFailureException: Record has both 260 and 264 fields; this is a cataloguing error.
  32 uk.ac.wellcome.exceptions.GracefulFailureException: Unable to find subfield $a?  List()
   8 uk.ac.wellcome.exceptions.GracefulFailureException: Unable to find subfield $a?  List(MarcSubfield(e,producer))
   8 uk.ac.wellcome.exceptions.GracefulFailureException: Unable to find subfield $a?  List(MarcSubfield(e,producer, ), MarcSubfield(e,director))
   8 uk.ac.wellcome.exceptions.GracefulFailureException: Unable to find subfield $a?  List(MarcSubfield(e,producer.))
 464 uk.ac.wellcome.exceptions.GracefulFailureException: Unrecognised location type: [none]
  56 uk.ac.wellcome.exceptions.GracefulFailureException: Unrecognised location type: [searb]
  16 uk.ac.wellcome.exceptions.GracefulFailureException: Unrecognised location type: [sg#er]
  80 uk.ac.wellcome.exceptions.GracefulFailureException: Unrecognised location type: [sgmip]
1256 uk.ac.wellcome.exceptions.GracefulFailureException: Unrecognised location type: [sgzin]
1584 uk.ac.wellcome.exceptions.GracefulFailureException: Unrecognised second indicator for production function: [Some( )]
```
