### ISSUE TITLE
Archive Service Integration Buglist

### ISSUE THREAD

**Issue by kenoir** [wellcometrust/platform#2936]
This issue is intended to collect issues arising from the archive service integration that need to be dealt with for the MVP.

- 500s from Bag API on "cold" requests.
- Archivist sometimes "Unable to execute HTTP request: Timeout waiting for connection from pool" (#2940)

**Comment by alexwlchan** [comment]
The 500 from the bag API appears to be coming from a timeout (and isn't just the /bags API). Here’s a stack trace from the Flask app:

```
2018-10-30 12:55:55,571 [63] WARNING  root: HTTPConnectionPool(host='registrar_http.archive-storage', port=9001): Read timed out. (read timeout=1)
2018-10-30 12:55:55,573 [63] ERROR    flask.app: Exception on /storage/v1/bags/bububa/b21508628 [GET]
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/urllib3/connectionpool.py", line 384, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/usr/lib/python3.6/site-packages/urllib3/connectionpool.py", line 380, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.6/http/client.py", line 1331, in getresponse
    response.begin()
  File "/usr/lib/python3.6/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.6/http/client.py", line 258, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.6/socket.py", line 586, in readinto
    return self._sock.recv_into(b)
socket.timeout: timed out
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/requests/adapters.py", line 445, in send
    timeout=timeout
  File "/usr/lib/python3.6/site-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/lib/python3.6/site-packages/urllib3/util/retry.py", line 367, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/lib/python3.6/site-packages/urllib3/packages/six.py", line 686, in reraise
    raise value
  File "/usr/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/usr/lib/python3.6/site-packages/urllib3/connectionpool.py", line 386, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/usr/lib/python3.6/site-packages/urllib3/connectionpool.py", line 306, in _raise_timeout
    raise ReadTimeoutError(self, url, "Read timed out. (read timeout=%s)" % timeout_value)
urllib3.exceptions.ReadTimeoutError: HTTPConnectionPool(host='registrar_http.archive-storage', port=9001): Read timed out. (read timeout=1)
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/lib/python3.6/site-packages/flask_restplus/api.py", line 325, in wrapper
    resp = resource(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/flask/views.py", line 88, in view
    return self.dispatch_request(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/flask_restplus/resource.py", line 44, in dispatch_request
    resp = meth(*args, **kwargs)
  File "./apis/bags.py", line 38, in get
    return bags_manager.lookup_bag(space, id)
  File "./bags_manager.py", line 22, in lookup_bag
    resp = self.sess.get(f"{self.endpoint}/registrar/{space}/{id}", timeout=1)
  File "/usr/lib/python3.6/site-packages/requests/sessions.py", line 525, in get
    return self.request('GET', url, **kwargs)
  File "/usr/lib/python3.6/site-packages/requests/sessions.py", line 512, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3.6/site-packages/requests/sessions.py", line 622, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3.6/site-packages/requests/adapters.py", line 526, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPConnectionPool(host='registrar_http.archive-storage', port=9001): Read timed out. (read timeout=1)
```

Key is this bit:

```
  File "./bags_manager.py", line 22, in lookup_bag
    resp = self.sess.get(f"{self.endpoint}/registrar/{space}/{id}", timeout=1)
```

If the progress API can’t respond within a second (which can happen if the JVM is cold), the Flask app throws a 500 error.

There aren't any logs in the same time period for the registrar-http app, which suggests there wasn’t a malign reason for the timeout. Bumping the timeout or ditching the Flask app should fix the error, and since the latter is on the cards I think we can skip the rest.

**Comment by kenoir** [comment]
Closing as "we've done things to fix these but we need to exercise the service a bit to see if they're really gone and if they aren't we'll reopen a bug list"
