### ISSUE TITLE
Reliably complete 10% bagging without error

### ISSUE THREAD

**Issue by jtweed** [wellcometrust/platform#3302]

**Comment by kenoir** [comment]
```

b18034895 | 2019-03-11 22:41:09+00:00 KeyError: 'Expecting one DeliverableUnit XML block; saw 0'
-- | --
b21782465 | 2019-03-11 17:55:20+00:00 RuntimeError: Unable to find asset 59d752db-5f2e-4490-9244-ea512fd18297
b10005055 | 2019-03-11 16:06:07+00:00 RuntimeError: Unable to find asset 546bc860-3fdf-4da6-915b-65292a906f4b
b29495805 | 2019-03-11 10:32:10+00:00 json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
b28733125 | 2019-03-11 12:02:24+00:00 RuntimeError: Unable to find asset 5cdb0b56-cf04-478f-926c-488e68e2631c
b21133815 | 2019-03-11 11:42:05+00:00 KeyError: 'Expecting one DeliverableUnit XML block; saw 0'
b18021335 | 2019-03-11 13:45:39+00:00 KeyError: 'JPEG2000 / Macintosh PICT Image 1.0'
b20458265 | 2019-03-11 17:46:58+00:00 RuntimeError: Unable to find asset 90aeb2d6-0a90-4a77-9494-35ba2ce0445d
b29825805 | 2019-03-11 10:32:10+00:00 json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
b24758905 | 2019-03-11 10:28:53+00:00 KeyError: 'Expecting one DeliverableUnit XML block; saw 0'
b12948305 | 2019-03-11 09:45:15+00:00 RuntimeError: Unable to find asset 65100aa5-f4b0-467d-a7fc-d61431d07913
b19263235 | 2019-03-11 13:40:47+00:00 IndexError: list index out of range
b16232665 | 2019-03-11 18:28:46+00:00 KeyError: 'Expecting one DeliverableUnit XML block; saw 0'
b10004385 | 2019-03-11 20:38:40+00:00 RuntimeError: Unable to find asset 71758a68-3113-4058-9520-f35c979c6980
b20442695 | 2019-03-11 22:19:28+00:00 RuntimeError: Unable to find asset b7294329-e79c-4f5e-8d71-3b8a43e26bbe
b21033365 | 2019-03-11 17:52:01+00:00 KeyError: 'Expecting one DeliverableUnit XML block; saw 0'
b18031535 | 2019-03-11 14:00:21+00:00 KeyError: 'JPEG2000 / Macintosh PICT Image 1.0'
```

Latest errors for '5' prefix.

**Comment by alexwlchan** [comment]
This is the complete traceback for that IndexError:

```
67 - MainThread - WARNING: Traceback (most recent call last):
  File "/opt/app/bagger_processor.py", line 27, in process_bagging_message
    identifier, do_not_bag
  File "/opt/app/bagger.py", line 42, in bag_from_identifier
    title = mets.get_title(root)
  File "/opt/app/mets.py", line 270, in get_title
    return title_el[0].text
IndexError: list index out of range
Could not process b19263235
```

**Comment by alexwlchan** [comment]
And here are the tracebacks for the JSONDecodeErrors:

```
70 - MainThread - WARNING: Traceback (most recent call last):
  File "/opt/app/bagger_processor.py", line 27, in process_bagging_message
    identifier, do_not_bag
  File "/opt/app/bagger.py", line 99, in bag_from_identifier
    process_manifestation(mf_root, bag_details, skip_  File_download, id_map)
  File "/opt/app/bagger.py", line 142, in process_manifestation
    Files.process_assets(root, bag_details, assets, tech_md_  Files, skip_  File_download)
  File "/opt/app/  Files.py", line 174, in process_assets
    fetch_attempt = try_to_download_asset(preservica_uuid, destination)
  File "/opt/app/  Files.py", line 232, in try_to_download_asset
    image_info = dlcs.get_image(preservica_uuid)
  File "/opt/app/dlcs.py", line 11, in get_image
    return response.json()
  File "/usr/lib/python3.6/site-packages/requests/models.py", line 897, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
Could not process b29825805


63 - MainThread - WARNING: Traceback (most recent call last):
  File "/opt/app/bagger_processor.py", line 27, in process_bagging_message
    identifier, do_not_bag
  File "/opt/app/bagger.py", line 108, in bag_from_identifier
    process_manifestation(root, bag_details, skip_  File_download, id_map)
  File "/opt/app/bagger.py", line 142, in process_manifestation
    Files.process_assets(root, bag_details, assets, tech_md_  Files, skip_  File_download)
  File "/opt/app/  Files.py", line 174, in process_assets
    fetch_attempt = try_to_download_asset(preservica_uuid, destination)
  File "/opt/app/  Files.py", line 232, in try_to_download_asset
    image_info = dlcs.get_image(preservica_uuid)
  File "/opt/app/dlcs.py", line 11, in get_image
    return response.json()
  File "/usr/lib/python3.6/site-packages/requests/models.py", line 897, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.6/json/decoder.py", line 357, in raw_decode
raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
Could not process b29495805
```

**Comment by kenoir** [comment]
```

Bagging Errors
--
b10005006 | 2019-03-12 16:06:10+00:00 RuntimeError: Unable to find asset a747819d-b39c-42d7-9f73-0c913e1682d3

```

One error for the `6` prefix.
