### ISSUE TITLE
Unpacker: Your proposed upload exceeds the maximum allowed size

### ISSUE THREAD

**Issue by alexwlchan** [wellcometrust/platform#3480]
Failure in last night’s unpacker run:

```
ERROR u.a.w.p.a.c.o.OperationNotifier - Failure - 715b3df1-9a42-4253-9e3d-c7ff2286b3c0 : 1 files 7077 bytes unpacked in PT0.665308S
com.amazonaws.services.s3.model.AmazonS3Exception: Your proposed upload exceeds the maximum allowed size (Service: Amazon S3; Status Code: 400; Error Code: EntityTooLarge; Request ID: 8336AEB8E7659A10; S3 Extended Request ID: QbtlGXzm6+L4LlYVpvowgYT6XFC2yiIodCxYnHPDki5W3EXzA9b+em0gxa4pWrkvOAinlHjV4Cg=)
    at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleErrorResponse(AmazonHttpClient.java:1632)
    at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1304)
    at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1058)
    at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:743)
    at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:717)
    at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:699)
    at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:667)
    at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:649)
    at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:513)
    at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4247)
    at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4194)
    at com.amazonaws.services.s3.AmazonS3Client.putObject(AmazonS3Client.java:1738)
    at uk.ac.wellcome.platform.archive.bagunpacker.services.Unpacker.putObject(Unpacker.scala:79)
    at uk.ac.wellcome.platform.archive.bagunpacker.services.Unpacker.$anonfun$unpack$2(Unpacker.scala:38)
    at uk.ac.wellcome.platform.archive.bagunpacker.storage.Archive$ArchiveReader.$anonfun$accumulate$2(Archive.scala:86)
    at scala.util.Try$.apply(Try.scala:209)
    at uk.ac.wellcome.platform.archive.bagunpacker.storage.Archive$ArchiveReader.accumulate(Archive.scala:82)
    at uk.ac.wellcome.platform.archive.bagunpacker.storage.Archive$.foldStream$1(Archive.scala:39)
    at uk.ac.wellcome.platform.archive.bagunpacker.storage.Archive$.$anonfun$unpack$1(Archive.scala:49)
    at scala.concurrent.Future$.$anonfun$apply$1(Future.scala:654)
    at scala.util.Success.$anonfun$map$1(Try.scala:251)
    at scala.util.Success.map(Try.scala:209)
    at scala.concurrent.Future.$anonfun$map$1(Future.scala:288)
    at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:29)
    at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:29)
    at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:60)
    at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:55)
    at akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:91)
    at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
    at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:81)
    at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:91)
    at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:40)
    at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:44)
    at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
    at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
    at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
    at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
```

For #3303.

**Comment by alexwlchan** [comment]
Also:

```
ERROR u.a.w.p.a.c.o.OperationNotifier - Failure - d3bad391-9b32-4ab4-a382-fdf5b76e3502 : 2 files 10833 bytes unpacked in PT1.199608S
```

**Comment by alexwlchan** [comment]
Given that the original bag this is part of made it into S3, I wonder if we’re calculating a value incorrectly somewhere?

**Comment by alexwlchan** [comment]
Affected bags:

- b2397817x.tar.gz
- b1672527x.tar.gz
- b1669157x.tar.gz

**Comment by alexwlchan** [comment]
Aha! Googling suggests that the problem is actually because we're trying to do a single part upload, and for big files we should fall back to a MultipartUpload.

I’m having a bit of trouble reproducing in tests, because IntelliJ seems to have got stuck.
