### ISSUE TITLE
Bag replicator: Internal error from S3

### ISSUE THREAD

**Issue by alexwlchan** [wellcometrust/platform#3482]
From this morning’s replicator run:

```
ERROR u.a.w.p.a.c.o.OperationNotifier - Failure: b38c49fe-9ef1-4142-be66-2dde15011b43: ReplicationSummary(2019-03-08T06:17:57.931050Z,Some(2019-03-08T06:19:11.575890Z),BagLocation(wellcomecollection-storage-staging-ingests,Some(unpacked),digitised,b38c49fe-9ef1-4142-be66-2dde15011b43),None)
com.amazonaws.services.s3.model.AmazonS3Exception: We encountered an internal error. Please try again. (Service: Amazon S3; Status Code: 500; Error Code: InternalError; Request ID: 3A1BB8F7332DFE76; S3 Extended Request ID: /sd6xxQwrgwwoTT5GIt8iiebxfjw3OBm/UtlpMEJbQpnwZdgr44dNnUSZ275kNz7dG3sJSTN9bI=)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleErrorResponse(AmazonHttpClient.java:1632)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1304)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1058)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:743)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:717)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:699)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:667)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:649)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:513)
	at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4247)
	at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4194)
	at com.amazonaws.services.s3.AmazonS3Client.copyObject(AmazonS3Client.java:1870)
	at com.amazonaws.services.s3.transfer.internal.CopyCallable.copyInOneChunk(CopyCallable.java:146)
	at com.amazonaws.services.s3.transfer.internal.CopyCallable.call(CopyCallable.java:134)
	at com.amazonaws.services.s3.transfer.internal.CopyMonitor.call(CopyMonitor.java:133)
	at com.amazonaws.services.s3.transfer.internal.CopyMonitor.call(CopyMonitor.java:44)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

It’s not clear to me what happened next – the storage manifest has the following events, which makes it sound like we marked it as succeeded anyway? That can’t be right – but then I don’t think we retry failed events?

```
            {'createdDate': '2019-02-27T14:35:56.377165Z',
             'description': 'Bag replicated successfully',
             'type': 'ProgressEvent'},
            {'createdDate': '2019-02-27T14:35:56.696794Z',
             'description': 'Failed to create storage manifest',
             'type': 'ProgressEvent'}],
```

We should understand what’s going on here, and make our apps resilient to these transient S3 errors, because this isn’t the first time I’ve seen one.

For #3303.

**Comment by alexwlchan** [comment]
Pretty sure the replicator retries this now, and it's been months, so closing.
