### ISSUE TITLE
Archivematica dashboard can't connect to the storage service

### ISSUE THREAD

**Issue by alexwlchan** [wellcometrust/platform#3494]
This is weird, because it used to work:

```
WARNING 2019-03-20 14:40:56 archivematica.common:storageService:get_pipeline:134: Error fetching pipeline
Traceback (most recent call last):
  File "/src/archivematicaCommon/lib/storageService.py", line 129, in get_pipeline
    response = _storage_api_session().get(url)
  File "/usr/local/lib/python2.7/site-packages/requests/sessions.py", line 546, in get
    return self.request('GET', url, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/src/archivematicaCommon/lib/storageService.py", line 69, in send
    return super(HTTPAdapterWithTimeout, self).send(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/requests/adapters.py", line 529, in send
    raise ReadTimeout(e, request=request)
ReadTimeout: HTTPConnectionPool(host='am-storage-service.archivematica', port=8000): Read timed out. (read timeout=5.0)
```

Possibly it’s hitting a timeout if they’re too far apart?

**Comment by alexwlchan** [comment]
Doesn’t seem like it – `exec`'ing into the container and testing the connection with cURL works fine.
