### ISSUE TITLE
Error in the Archivematica dashboard logs

### ISSUE THREAD

**Issue by alexwlchan** [wellcometrust/platform#3495]
Spotted just now:

```
ERROR 2019-03-20 14:40:49 django.request:base:handle_uncaught_exception:256: Internal Server Error: /access/archivesspace/levels/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/src/dashboard/src/components/access/views.py", line 48, in wrapper
    client = _get_client_by_type(system)
  File "/src/dashboard/src/components/access/views.py", line 35, in _get_client_by_type
    return get_as_system_client()
  File "/src/dashboard/src/components/ingest/views_as.py", line 25, in get_as_system_client
    if not config['host']:
KeyError: 'host'
```

**Comment by jtweed** [comment]
Closing to tidy up the backlog. Will reopen as a new issue if we see it again with our actual workflow.
