### ISSUE TITLE
Intermittent failure of Characterize during Process submission documentation

### ISSUE THREAD

**Issue by helenst** [wellcometrust/platform#3511]
Example of failure

https://archivematica.wellcomecollection.org/tasks/afc2d7a0-7b1b-4ca3-9604-0d1970a0b96f/

```
File matching query does not exist.Traceback (most recent call last):
  File "/src/MCPClient/lib/job.py", line 102, in JobContext
    yield
  File "/src/MCPClient/lib/clientScripts/characterize_file.py", line 107, in call
    job.set_status(main(job, *job.args[1:]))
  File "/src/MCPClient/lib/clientScripts/characterize_file.py", line 62, in main
    file_=file_uuid, sip=sip_uuid, type_='file')
  File "/src/archivematicaCommon/lib/dicts.py", line 54, in replace_string_values
    rd = ReplacementDict.frommodel(**kwargs)
  File "/src/archivematicaCommon/lib/dicts.py", line 99, in frommodel
    file_ = models.File.objects.get(uuid=file_)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/manager.py", line 127, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 334, in get
    self.model._meta.object_name
DoesNotExist: File matching query does not exist.
```

Most likely related to #3510 as they happen together and are giving the same error.

Example of success:
https://archivematica.wellcomecollection.org/tasks/7aa78bb1-9a6d-4976-a23c-7fd67499bd6c/
(blank output)

**Comment by helenst** [comment]
As with #3510, filesystem sync issues mean METS.xml doesn't get a UUID or a `File` database entry during an earlier step, so this step fails trying to look it up.
