### ISSUE TITLE
Unpacker doesn't have access to uploads in the ingests bucket from Archivematica

### ISSUE THREAD

**Issue by alexwlchan** [wellcometrust/platform#3524]
```
java.lang.RuntimeException: Error getting input stream for s3://wellcomecollection-storage-ingests/archivematica/aips/1839/64cd/5758/4fb0/97e9/33a7/698e/9178/PPTHW_2466-183964cd-5758-4fb0-97e9-33a7698e9178.zip: Access Denied (Service: Amazon S3; Status Code: 403; Error Code: AccessDenied; Request ID: DA5618898730426B; S3 Extended Request ID: V0HMJWfdALRqxrEEkKJ+k7fC0ySt4tcrAs8GOZvZ4XOW1oV7Fx+vicyB
java.lang.RuntimeException: Error getting input stream for s3://wellcomecollection-storage-ingests/archivematica/aips/1839/64cd/5758/4fb0/97e9/33a7/698e/9178/PPTHW_2466-183964cd-5758-4fb0-97e9-33a7698e9178.zip: Access Denied (Service: Amazon S3; Status Code: 403; Error Code: AccessDenied; Request ID: DA5618898730426B; S3 Extended Request ID: V0HMJWfdALRqxrEEkKJ+k7fC0ySt4tcrAs8GOZvZ4XOW1oV7Fx+vicyB0WgNv6pfwKXai9qclIA=)
    at uk.ac.wellcome.platform.archive.common.ConvertibleToInputStream$ConvertibleToInputStreamObjectLocation$$anonfun$apply$3.applyOrElse(ConvertibleToInputStream.scala:33)
    at uk.ac.wellcome.platform.archive.common.ConvertibleToInputStream$ConvertibleToInputStreamObjectLocation$$anonfun$apply$3.applyOrElse(ConvertibleToInputStream.scala:30)
    at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:34)
    at scala.util.Failure.recover(Try.scala:230)
    at scala.concurrent.Future.$anonfun$recover$1(Future.scala:391)
    at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:29)
    at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:29)
    at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:60)
    at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:55)
    at akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:91)
    at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
    at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:81)
    at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:91)
    at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:40)
    at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:44)
    at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
    at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
    at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
    at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
```

**Comment by alexwlchan** [comment]
Can reproduce locally:

```python
import boto3

sts = boto3.client("sts")
resp = sts.assume_role(
    RoleArn="arn:aws:iam::975596993436:role/storage-stewart-bag-unpacker_task_role",
    RoleSessionName="alex-repro-3524"
)

credentials = resp["Credentials"]

s3 = boto3.client(
    "s3",
    aws_access_key_id=credentials["AccessKeyId"],
    aws_secret_access_key=credentials["SecretAccessKey"],
    aws_session_token=credentials["SessionToken"]
)

s3.get_object(
    Bucket="wellcomecollection-storage-ingests",
    Key="archivematica/aips/1839/64cd/5758/4fb0/97e9/33a7/698e/9178/PPTHW_2466-183964cd-5758-4fb0-97e9-33a7698e9178.zip"
)
```

**Comment by alexwlchan** [comment]
This is the JSON that allegedly assigns an IAM policy for the task role to access the bucket:

```json
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "",
            "Effect": "Allow",
            "Action": "s3:ListBucket",
            "Resource": "arn:aws:s3:::wellcomecollection-storage-ingests"
        },
        {
            "Sid": "",
            "Effect": "Allow",
            "Action": [
                "s3:PutObject*",
                "s3:GetObject*"
            ],
            "Resource": "arn:aws:s3:::wellcomecollection-storage-ingests/*"
        }
    ]
}
```

Notably, doing a PutObject against the bucket works fine.

**Comment by alexwlchan** [comment]
And it’s not something about the key, I just did a Put+Get on `<AM_KEY>.test` and it worked.

**Comment by alexwlchan** [comment]
This looks like the issue: there are no permissions on the object itself.

![Screenshot 2019-03-28 at 09 50 22](https://user-images.githubusercontent.com/301220/55147808-fb73c000-513e-11e9-8c30-1c27a74950be.png)
![Screenshot 2019-03-28 at 09 50 29](https://user-images.githubusercontent.com/301220/55147810-fb73c000-513e-11e9-8285-f4745ffa76f1.png)

**Comment by alexwlchan** [comment]
Ha ha ha, I think we might have created an undelete-able object.
