### ISSUE TITLE
An exception in AlpakkaSQSWorker causes the entire app to hang

### ISSUE THREAD

**Issue by alexwlchan** [wellcometrust/platform#3611]
Witness the bag replicator:

```
ERROR u.a.w.p.archive.bagreplicator.Main$ - Fatal error:
com.amazonaws.services.sqs.model.AmazonSQSException: Access to the resource https://sqs.eu-west-1.amazonaws.com/975596993436/storage_colbert_bag_replicator_input is denied. (Service: AmazonSQS; Status Code: 403; Error Code: AccessDenied; Request ID: 3f34424a-200d-5e5f-a185-170c67eb35a8)
    at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleErrorResponse(AmazonHttpClient.java:1632)
    at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1304)
    at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1058)
    at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:743)
    at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:717)
    at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:699)
    at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:667)
    at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:649)
    at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:513)
    at com.amazonaws.services.sqs.AmazonSQSClient.doInvoke(AmazonSQSClient.java:2033)
    at com.amazonaws.services.sqs.AmazonSQSClient.invoke(AmazonSQSClient.java:2009)
    at com.amazonaws.services.sqs.AmazonSQSClient.executeChangeMessageVisibility(AmazonSQSClient.java:520)
    at com.amazonaws.services.sqs.AmazonSQSAsyncClient$2.call(AmazonSQSAsyncClient.java:402)
    at com.amazonaws.services.sqs.AmazonSQSAsyncClient$2.call(AmazonSQSAsyncClient.java:396)
    at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
    at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
    at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
    at java.base/java.lang.Thread.run(Thread.java:834)
INFO u.a.w.p.archive.bagreplicator.Main$ - Terminating worker.
```

**Comment by alexwlchan** [comment]
Duplicate of #4046.
