### ISSUE TITLE
Unpacker: not all errors appear to the user?

### ISSUE THREAD

**Issue by alexwlchan** [wellcometrust/platform#3808]
See ingest 55813578-0d60-46d8-89eb-fb869953b58d

It only has one event and the status is still `processing`:

```json
  "events": [
    {
      "createdDate": "2019-08-06T12:29:52.866Z",
      "description": "Unpacking started",
      "type": "IngestEvent"
    }
  ],
```

But there's a pretty long stack trace in the unpacker logs that suggests something went wrong (I tried to unpack a bag in a staging bucket in the prod API):

```
12:29:53.103 [main-actor-system-akka.actor.default-dispatcher-10] ERROR u.a.w.p.a.c.s.m.IngestStepWorker$$anon$1 - DeterministicFailure(com.amazonaws.services.s3.model.AmazonS3Exception: Access Denied (Service: Amazon S3; Status Code: 403; Error Code: AccessDenied; Request ID: 44513C6DFF1B77F5; S3 Extended Request ID: feWE5hFZt1qQste0F9K5pvwAM38XQohvc6ndPhkhcnJbLojVqTeXMWWibUuOrHRE7nav1JHZ/JE=), S3 Extended Request ID: feWE5hFZt1qQste0F9K5pvwAM38XQohvc6ndPhkhcnJbLojVqTeXMWWibUuOrHRE7nav1JHZ/JE=,Some(id=55813578-0d60-46d8-89eb-fb869953b58d, src=wellcomecollection-storage-staging-bagger-drop/b2227683x-fixed.tar.gz, dst=ObjectLocationPrefix(wellcomecollection-storage-ingests,unpacked/digitised/55813578-0d60-46d8-89eb-fb869953b58d), files=0, bytesSize=0, size=0 bytes, durationSeconds=0, duration=<not-completed>))
com.amazonaws.services.s3.model.AmazonS3Exception: Access Denied (Service: Amazon S3; Status Code: 403; Error Code: AccessDenied; Request ID: 44513C6DFF1B77F5; S3 Extended Request ID: feWE5hFZt1qQste0F9K5pvwAM38XQohvc6ndPhkhcnJbLojVqTeXMWWibUuOrHRE7nav1JHZ/JE=)
at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleErrorResponse(AmazonHttpClient.java:1712)
at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1367)
at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1113)
at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:770)
at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:744)
at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:726)
at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:686)
at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:668)
at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:532)
at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:512)
at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4914)
at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4860)
at com.amazonaws.services.s3.AmazonS3Client.getObject(AmazonS3Client.java:1467)
at com.amazonaws.services.s3.AmazonS3Client.getObject(AmazonS3Client.java:1326)
at uk.ac.wellcome.storage.store.s3.S3StreamStore.$anonfun$get$1(S3StreamStore.scala:26)
at scala.util.Try$.apply(Try.scala:209)
at uk.ac.wellcome.storage.store.s3.S3StreamStore.get(S3StreamStore.scala:26)
at uk.ac.wellcome.platform.archive.bagunpacker.services.s3.S3Unpacker.get(S3Unpacker.scala:29)
at uk.ac.wellcome.platform.archive.bagunpacker.services.Unpacker.unpack(Unpacker.scala:45)
at uk.ac.wellcome.platform.archive.bagunpacker.services.Unpacker.unpack$(Unpacker.scala:36)
at uk.ac.wellcome.platform.archive.bagunpacker.services.s3.S3Unpacker.unpack(S3Unpacker.scala:24)
at uk.ac.wellcome.platform.archive.bagunpacker.services.BagUnpackerWorker.$anonfun$processMessage$2(BagUnpackerWorker.scala:50)
at scala.util.Success.flatMap(Try.scala:247)
at uk.ac.wellcome.platform.archive.bagunpacker.services.BagUnpackerWorker.processMessage(BagUnpackerWorker.scala:39)
at uk.ac.wellcome.platform.archive.bagunpacker.services.BagUnpackerWorker.processMessage(BagUnpackerWorker.scala:24)
at uk.ac.wellcome.platform.archive.common.storage.models.IngestStepWorker.process(IngestStepResult.scala:78)
at uk.ac.wellcome.platform.archive.common.storage.models.IngestStepWorker.process$(IngestStepResult.scala:77)
at uk.ac.wellcome.platform.archive.bagunpacker.services.BagUnpackerWorker.process(BagUnpackerWorker.scala:24)
at uk.ac.wellcome.platform.archive.common.storage.models.IngestStepWorker$$anon$1$$anonfun$$lessinit$greater$1.apply(IngestStepResult.scala:82)
at uk.ac.wellcome.platform.archive.common.storage.models.IngestStepWorker$$anon$1$$anonfun$$lessinit$greater$1.apply(IngestStepResult.scala:82)
at uk.ac.wellcome.messaging.worker.steps.MessageProcessor.$anonfun$process$1(MessageProcessor.scala:18)
at scala.concurrent.Future.$anonfun$flatMap$1(Future.scala:303)
at scala.concurrent.impl.Promise.$anonfun$transformWith$1(Promise.scala:37)
at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:60)
at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:55)
at akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:91)
at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:81)
at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:91)
at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:40)
at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:44)
at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
No newer events found at the moment. Retry.
```

**Comment by alexwlchan** [comment]
I suspect this is the same issue as #3812.
