### ISSUE TITLE
Ingest 10% of the bags

### ISSUE THREAD

**Issue by alexwlchan** [wellcometrust/platform#3872]
* [x] Reduce the concurrency in the unpacker. It keeps having the error:

    > com.amazonaws.SdkClientException: Unable to execute HTTP request: Timeout waiting for connection from pool

* [x] Why is the ingests service dropping messages on the DLQ?

* [ ] Why is the unpacker complaining about TCP and logstash?

    > at java.net.UnknownHostException: storage-prod_logstash_transit.storage-prod

**Comment by alexwlchan** [comment]
One failure in the replica aggregator:

```
15:35:43.944 [main-actor-system-akka.actor.default-dispatcher-76] ERROR u.a.w.p.a.c.s.m.IngestStepWorker$$anon$1 - DeterministicFailure(java.lang.Error,Some(replicaPath=digitised/b29436102/v1, durationSeconds=0, duration=PT0.009446S, , status=failed, , ))
java.lang.Error: null
at uk.ac.wellcome.storage.VersionAlreadyExistsError$.apply$default$1(StorageError.scala:67)
at uk.ac.wellcome.storage.VersionAlreadyExistsError$.apply$default$1(StorageError.scala:67)
at uk.ac.wellcome.storage.store.VersionedStore.put(VersionedStore.scala:91)
at uk.ac.wellcome.storage.store.VersionedStore.upsert(VersionedStore.scala:59)
at uk.ac.wellcome.platform.storage.replica_aggregator.services.ReplicaAggregator.aggregate(ReplicaAggregator.scala:21)
at uk.ac.wellcome.platform.storage.replica_aggregator.services.ReplicaAggregatorWorker.getKnownReplicas(ReplicaAggregatorWorker.scala:54)
at uk.ac.wellcome.platform.storage.replica_aggregator.services.ReplicaAggregatorWorker.processMessage(ReplicaAggregatorWorker.scala:71)
at uk.ac.wellcome.platform.storage.replica_aggregator.services.ReplicaAggregatorWorker.processMessage(ReplicaAggregatorWorker.scala:24)
at uk.ac.wellcome.platform.archive.common.storage.models.IngestStepWorker.process(IngestStepResult.scala:78)
at uk.ac.wellcome.platform.archive.common.storage.models.IngestStepWorker.process$(IngestStepResult.scala:77)
at uk.ac.wellcome.platform.storage.replica_aggregator.services.ReplicaAggregatorWorker.process(ReplicaAggregatorWorker.scala:24)
at uk.ac.wellcome.platform.archive.common.storage.models.IngestStepWorker$$anon$1$$anonfun$$lessinit$greater$1.apply(IngestStepResult.scala:82)
at uk.ac.wellcome.platform.archive.common.storage.models.IngestStepWorker$$anon$1$$anonfun$$lessinit$greater$1.apply(IngestStepResult.scala:82)
at uk.ac.wellcome.messaging.worker.steps.MessageProcessor.$anonfun$process$1(MessageProcessor.scala:18)
at scala.concurrent.Future.$anonfun$flatMap$1(Future.scala:303)
at scala.concurrent.impl.Promise.$anonfun$transformWith$1(Promise.scala:37)
at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:60)
at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:55)
at akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:91)
at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:81)
at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:91)
at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:40)
at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:44)
at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
```
