### ISSUE TITLE
Replica aggregator can still throw an error sometimes

### ISSUE THREAD

**Issue by alexwlchan** [wellcometrust/platform#3896]
Spotted in today‘s CloudWatch logs:

```
[main-actor-system-akka.actor.default-dispatcher-6] ERROR u.a.w.p.a.c.s.m.IngestStepWorker$$anon$1 - DeterministicFailure(java.lang.Error,Some(replicaPath=digitised/b22362010/v1, status=failed, ingestId=58408609-1a19-4536-894a-45e8ec9713f8, duration=PT0.12577S, durationSeconds=0))
java.lang.Error: null
at uk.ac.wellcome.storage.VersionAlreadyExistsError$.apply$default$1(StorageError.scala:67)
at uk.ac.wellcome.storage.VersionAlreadyExistsError$.apply$default$1(StorageError.scala:67)
at uk.ac.wellcome.storage.store.VersionedStore.put(VersionedStore.scala:91)
at uk.ac.wellcome.storage.store.VersionedStore.upsert(VersionedStore.scala:59)
at uk.ac.wellcome.platform.storage.replica_aggregator.services.ReplicaAggregator.aggregate(ReplicaAggregator.scala:21)
at uk.ac.wellcome.platform.storage.replica_aggregator.services.ReplicaAggregatorWorker.getKnownReplicas(ReplicaAggregatorWorker.scala:54)
at uk.ac.wellcome.platform.storage.replica_aggregator.services.ReplicaAggregatorWorker.processMessage(ReplicaAggregatorWorker.scala:71)
at uk.ac.wellcome.platform.storage.replica_aggregator.services.ReplicaAggregatorWorker.processMessage(ReplicaAggregatorWorker.scala:24)
at uk.ac.wellcome.platform.archive.common.storage.models.IngestStepWorker.process(IngestStepResult.scala:78)
at uk.ac.wellcome.platform.archive.common.storage.models.IngestStepWorker.process$(IngestStepResult.scala:77)
at uk.ac.wellcome.platform.storage.replica_aggregator.services.ReplicaAggregatorWorker.process(ReplicaAggregatorWorker.scala:24)
at uk.ac.wellcome.platform.archive.common.storage.models.IngestStepWorker$$anon$1$$anonfun$$lessinit$greater$1.apply(IngestStepResult.scala:82)
at uk.ac.wellcome.platform.archive.common.storage.models.IngestStepWorker$$anon$1$$anonfun$$lessinit$greater$1.apply(IngestStepResult.scala:82)
at uk.ac.wellcome.messaging.worker.steps.MessageProcessor.$anonfun$process$1(MessageProcessor.scala:18)
at scala.concurrent.Future.$anonfun$flatMap$1(Future.scala:303)
at scala.concurrent.impl.Promise.$anonfun$transformWith$1(Promise.scala:37)
at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:60)
at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:55)
at akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:91)
at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:81)
at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:91)
at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:40)
at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:44)
at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
```

So in the same way `putLatest(…)` needs to be returning retryable errors, looks like update() and upsert() do as well.

**Comment by alexwlchan** [comment]
Closing as probably fixed now, will re-open if it reappears.
