### ISSUE TITLE
Archivematica is currently failing to start a reingest

### ISSUE THREAD

**Issue by helenst** [wellcometrust/platform#4004]
When attempting to kick off a full reingest of an AIP on Archivematica, an unknown error is reported.

**Comment by helenst** [comment]
The failure is occurring in `Package.get_base_directory()` as it is expecting a base directory within the compressed package.

**Comment by helenst** [comment]
We are not creating a top level directory in the archive when downloading and compressing the bag from S3. Perhaps we were before with the previous download/compression method.

**Comment by alexwlchan** [comment]
I've deployed an instance of am-storage-service with a newer client lib, looks like a similar issue.

Stack trace:

```
ERROR 2019-11-13 10:21:13 django.request.tastypie:resources:_handle_500:301: Internal Server Error: /api/v2/file/cc7c8e7d-64b8-4f80-8bc8-c72e77e87fec/reingest/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/tastypie/resources.py", line 220, in wrapper
    response = callback(request, *args, **kwargs)
  File "/src/storage_service/locations/api/resources.py", line 135, in wrapper
    result = func(resource, request, bundle, **kwargs)
  File "/src/storage_service/locations/api/resources.py", line 1537, in reingest_request
    response = bundle.obj.start_reingest(pipeline, reingest_type, processing_config)
  File "/src/storage_service/locations/models/package.py", line 2012, in start_reingest
    local_path, temp_dir = self.extract_file()
  File "/src/storage_service/locations/models/package.py", line 1476, in extract_file
    basename = self.get_base_directory()
  File "/src/storage_service/locations/models/package.py", line 361, in get_base_directory
    return directories[0]
IndexError: list index out of range
```

Tomorrow's task: add a bunch of tracing and work out where it's still going wrong.

**Comment by alexwlchan** [comment]
Aha! This is the code in question:

```python
if self.is_compressed:
    # Use lsar's JSON output to determine the directories in a
    # compressed file. Since the index of the base directory may
    # not be consistent, determine it by filtering all entries
    # for directories, then determine the directory with the
    # shortest name. (e.g. foo is the parent of foo/bar)
    # NOTE: lsar's JSON output is broken in certain circumstances in
    #       all released versions; make sure to use a patched version
    #       for this to work.
    command = ["lsar", "-ja", full_path]
    output = subprocess.check_output(command)
    output = json.loads(output)
    directories = [
        d["XADFileName"]
        for d in output["lsarContents"]
        if d.get("XADIsDirectory", False)
    ]
    directories = sorted(directories, key=len)
    return directories[0]
```

I think lsar's behaviour here is wrong (or sub-optimal), let me have a play.

**Comment by alexwlchan** [comment]
Okay, so I think it's less lsar itself, more the use of it. I think this is neater:

```python
import os

directories = set()

for lsar_entry in lsar["lsarContents"]:
    if lsar_entry.get("XADIsDirectory"):
        directories.add(lsar_entry["XADFileName"])
    else:
        dirname = os.path.dirname(lsar_entry["XADFileName"])
        directories.add(dirname)

sorted(directories)[0]
```

And could arguably be broken out into a separately tested utility method.

**Comment by alexwlchan** [comment]
I’ve deployed a fix to staging which seems to fix the initial error, but the reingest never appears in the ingests tab.

This error is appearing in the MCP server logs – I wonder if it’s related?

```
DEBUG 2019-11-14 17:09:08 archivematica.mcp.server:taskGroupRunner:_monitor_running_jobs:258: 0 jobs pending; 0 jobs running; 0 known task groups
DEBUG 2019-11-14 17:09:14 archivematica.mcp.server:watchDirectory:start:85: Added [u'64d6a348-3110-4e50-a02f-71bc68f53d8a']
DEBUG 2019-11-14 17:09:14 archivematica.mcp.server:archivematicaMCP:createUnitAndJobChainThreaded:179: Watching path /var/archivematica/sharedDirectory/watchedDirectories/activeTransfers/standardTransfer/64d6a348-3110-4e50-a02f-71bc68f53d8a
DEBUG 2019-11-14 17:09:14 archivematica.mcp.server:archivematicaMCP:createUnitAndJobChain:155: Starting chain for /var/archivematica/sharedDirectory/watchedDirectories/activeTransfers/standardTransfer/64d6a348-3110-4e50-a02f-71bc68f53d8a/
DEBUG 2019-11-14 17:09:14 archivematica.mcp.server:jobChain:__init__:64: Creating jobChain unitTransfer: <UUID: 64d6a348-3110-4e50-a02f-71bc68f53d8a, path: %sharedPath%watchedDirectories/activeTransfers/standardTransfer/64d6a348-3110-4e50-a02f-71bc68f53d8a/> for chain fffd5342-2337-463f-857a-b2c8c3778c6d
DEBUG 2019-11-14 17:09:14 archivematica.mcp.server:jobChain:__init__:70: Chain: fffd5342-2337-463f-857a-b2c8c3778c6d
DEBUG 2019-11-14 17:09:14 archivematica.mcp.server:jobChain:fetchUnitVariableForUnit:56: Replacement dict for unit 64d6a348-3110-4e50-a02f-71bc68f53d8a: {}
INFO 2019-11-14 17:09:14 archivematica.mcp.server:jobChainLink:__init__:52: Running Approve standard transfer (unit 64d6a348-3110-4e50-a02f-71bc68f53d8a)
ERROR 2019-11-14 17:09:14 archivematica.mcp.server:utils:wrapped:18: Uncaught exception
Traceback (most recent call last):
  File "/src/MCPServer/lib/utils.py", line 16, in wrapped
    return fn(*args, **kwargs)
  File "/src/archivematicaCommon/lib/databaseFunctions.py", line 45, in wrapper
    return f(*args, **kwargs)
  File "/src/MCPServer/lib/archivematicaMCP.py", line 174, in createUnitAndJobChain
    jobChain(unit, watched_dir.chain, workflow)
  File "/src/MCPServer/lib/jobChain.py", line 81, in __init__
    jobChainLink(self, starting_link, workflow, unit, passVar=rd)
  File "/src/MCPServer/lib/jobChainLink.py", line 53, in __init__
    self.unit.reload()
  File "/src/MCPServer/lib/unitTransfer.py", line 71, in reload
    transfer = Transfer.objects.get(uuid=self.UUID)
  File "/usr/local/lib/python2.7/site-packages/django/db/models/manager.py", line 127, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/django/db/models/query.py", line 334, in get
    self.model._meta.object_name
DoesNotExist: Transfer matching query does not exist.
```

**Comment by alexwlchan** [comment]
Further digging: a metadata re-ingest shows up in the Ingest tab and succeeds; a partial or full re-ingest does not.

![Screenshot 2019-11-19 at 10 48 21](https://user-images.githubusercontent.com/301220/69140332-38b80400-0aba-11ea-81b5-6eaab0a44279.png)
![Screenshot 2019-11-19 at 10 48 28](https://user-images.githubusercontent.com/301220/69140334-39509a80-0aba-11ea-8a01-81a5e93dbcc4.png)

**Comment by alexwlchan** [comment]
Here's an interesting error I just encountered (I think separately) when trying to reingest an already-ingested bag. Storage service logs:

```
DEBUG 2019-11-19 03:12:33 locations.models.wellcome:wellcome:move_to_storage_service:110: Fetching /born-digital/87e9/eced/8a96/49a2/a40b/47b4/9808/730e/87e9eced-8a96-49a2-a40b-47b49808730e.tar.gz on Wellcome storage to /var/archivematica/storage_service/87e9/eced/8a96/49a2/a40b/47b4/9808/730e/87e9eced-8a96-49a2-a40b-47b49808730e.tar.gz (space 9c23bc8a-6881-4247-be0b-231c37cd7f60: / (Local F
ERROR 2019-11-19 03:12:33 django.request.tastypie:resources:_handle_500:301: Internal Server Error: /api/v2/file/87e9eced-8a96-49a2-a40b-47b49808730e/reingest/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/tastypie/resources.py", line 220, in wrapper
    response = callback(request, *args, **kwargs)
  File "/src/storage_service/locations/api/resources.py", line 135, in wrapper
    result = func(resource, request, bundle, **kwargs)
  File "/src/storage_service/locations/api/resources.py", line 1537, in reingest_request
    response = bundle.obj.start_reingest(pipeline, reingest_type, processing_config)
  File "/src/storage_service/locations/models/package.py", line 1995, in start_reingest
    if self.is_compressed:
  File "/src/storage_service/locations/models/package.py", line 206, in is_compressed
    full_path = self.fetch_local_path()
  File "/src/storage_service/locations/models/package.py", line 304, in fetch_local_path
    package=self,
  File "/src/storage_service/locations/models/space.py", line 361, in move_to_storage_service
    source_path, destination_path, destination_space, *args, **kwargs
  File "/src/storage_service/locations/models/wellcome.py", line 140, in move_to_storage_service
    bag = self.wellcome_client.get_bag(**bag_kwargs)
  File "/usr/local/lib/python2.7/site-packages/wellcome_storage_service/__init__.py", line 56, in wrapper
    return f(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/wellcome_storage_service/__init__.py", line 36, in wrapper
    resp = f(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/wellcome_storage_service/__init__.py", line 167, in get_bag
    raise BagNotFound(err)
BagNotFound: Bags API returned 404 for bag born-digital/8a96-49a2-a40b-47b49808730e with version v2
```

I wonder if Archivematica versioning is a bit confused?

**Comment by alexwlchan** [comment]
Logs from the storage service after what looks like a successful reingest:

```
11:13:16
DEBUG 2019-11-19 03:13:16 locations.models.package:package:start_reingest:1997: Reingest: extracted to /var/archivematica/storage_service/tmpvO5mCc/ba9f48bf-bd0d-47be-8af5-77955f94d293
DEBUG 2019-11-19 03:13:16 locations.models.package:package:start_reingest:2008: Reingest: Fixity response: True,
INFO 2019-11-19 03:13:16 locations.models.package:package:start_reingest:2073: Reingest: files: [u'tmpvO5mCc/ba9f48bf-bd0d-47be-8af5-77955f94d293']
DEBUG 2019-11-19 03:13:16 locations.models.package:package:start_reingest:2089: Reingest: Current location: f4f67e1b-e889-43cf-9680-570e9fb1c354: var/archivematica/storage_service (Storage Service Internal Processing)
DEBUG 2019-11-19 03:13:17 locations.models.pipeline:pipeline:_request_api:194: URL: https://archivematica-stage.wellcomecollection.org/api/transfer/reingest; headers {'Authorization': 'ApiKey admin:555e313d435ada9b5567838a3f96c74db0aae5b8b75571aea091a734f2db8682'}; data: {'name': u'tmpvO5mCc/ba9f48bf-bd0d-47be-8af5-77955f94d293', 'uuid': u'ba9f48bf-bd0d-47be-8af5-77955f94d293'}
DEBUG 2019-11-19 03:13:17 locations.models.pipeline:pipeline:_request_api:209: Response: 200 {"message": "Approval successful.", "reingest_uuid": "e64a1d1f-2aca-4017-ab92-6dce6860f7c1"}
DEBUG 2019-11-19 03:13:17 locations.models.package:package:start_reingest:2126: Reingest UUID: e64a1d1f-2aca-4017-ab92-6dce6860f7c1
127.0.0.1 - - [19/Nov/2019:03:13:17 -0800] "POST /api/v2/file/ba9f48bf-bd0d-47be-8af5-77955f94d293/reingest/ HTTP/1.0" 202 280 "-" "python-requests/2.21.0"
```

**Comment by helenst** [comment]
It looks as if the reingest is getting put into the watched transfer directory. (`/var/archivematica/sharedDirectory/watchedDirectories/activeTransfers/standardTransfer/`) - I wonder why it's not being picked up. This would be MCP Server's job.

**Comment by helenst** [comment]
Ah, and now I'm seeing that same error in MCP Server logs when it tries to pick up the transfer (Transfer matching query does not exist). This would be related. I'll dig deeper after lunch and see what I can figure out.

**Comment by helenst** [comment]
So the transfer database entry definitely doesn't exist for Wellcome-stored reingests but it does for local-stored ones. Next step is to compare the code in dashboard which should be creating those entries.

**Comment by helenst** [comment]
maybe related to name being missing from sip name (i.e. it's just the UUID) when reingest endpoint is called (components/api/views.py). I think this results in the wrong transfer path being used, and MCP Server tries to use the wrong path to look up the transfer.

Next: see why storage service is not getting the name correct when it calls the endpoint.

**Comment by helenst** [comment]
OK... it's because the path derives from the base directory seen inside the compressed archive. This is just the UUID (bag external ID). It seems that Archivematica makes some assumptions about how that directory name is formatted. I think it would work if formatted NAME-uuid.... trying this now

**Comment by helenst** [comment]
This works. I think the answer is to allow `download_compressed_bag` to accept an optional directory argument (but still default to external_id)
