### ISSUE TITLE
Replica aggregator: still reporting version conflicts as deterministic sometimes

### ISSUE THREAD

**Issue by alexwlchan** [wellcometrust/platform#4048]
Stack trace:

```
14:37:10.729 [main-actor-system-akka.actor.default-dispatcher-169] ERROR u.a.w.p.a.c.s.m.IngestStepWorker$$anon$1 - DeterministicFailure(java.lang.Error,Some(replicaPath=digitised/b31478864/v1, status=failed, ingestId=57950b92-8c55-4be0-836b-7b79f8822168, duration=PT0.054691S, durationSeconds=0))
java.lang.Error: null
at uk.ac.wellcome.storage.VersionAlreadyExistsError$.apply$default$1(StorageError.scala:67)
at uk.ac.wellcome.storage.VersionAlreadyExistsError$.apply$default$1(StorageError.scala:67)
at uk.ac.wellcome.storage.store.VersionedStore.put(VersionedStore.scala:100)
at uk.ac.wellcome.storage.store.VersionedStore.upsert(VersionedStore.scala:68)
at uk.ac.wellcome.platform.storage.replica_aggregator.services.ReplicaAggregator.aggregate(ReplicaAggregator.scala:21)
at uk.ac.wellcome.platform.storage.replica_aggregator.services.ReplicaAggregatorWorker.getKnownReplicas(ReplicaAggregatorWorker.scala:54)
at uk.ac.wellcome.platform.storage.replica_aggregator.services.ReplicaAggregatorWorker.processMessage(ReplicaAggregatorWorker.scala:71)
at uk.ac.wellcome.platform.storage.replica_aggregator.services.ReplicaAggregatorWorker.processMessage(ReplicaAggregatorWorker.scala:24)
at uk.ac.wellcome.platform.archive.common.storage.models.IngestStepWorker.process(IngestStepResult.scala:78)
at uk.ac.wellcome.platform.archive.common.storage.models.IngestStepWorker.process$(IngestStepResult.scala:77)
at uk.ac.wellcome.platform.storage.replica_aggregator.services.ReplicaAggregatorWorker.process(ReplicaAggregatorWorker.scala:24)
at uk.ac.wellcome.platform.archive.common.storage.models.IngestStepWorker$$anon$1$$anonfun$$lessinit$greater$1.apply(IngestStepResult.scala:82)
at uk.ac.wellcome.platform.archive.common.storage.models.IngestStepWorker$$anon$1$$anonfun$$lessinit$greater$1.apply(IngestStepResult.scala:82)
at uk.ac.wellcome.messaging.worker.steps.MessageProcessor.$anonfun$process$1(MessageProcessor.scala:18)
at scala.concurrent.Future.$anonfun$flatMap$1(Future.scala:303)
at scala.concurrent.impl.Promise.$anonfun$transformWith$1(Promise.scala:37)
at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:60)
at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:55)
at akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:91)
at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:81)
at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:91)
at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:40)
at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:44)
at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
```

Ingest IDs:

* b31478864 - 57950b92-8c55-4be0-836b-7b79f8822168
* b31492599 - 312de5a6-484e-4b3f-8d6c-f49710f4de82

**Comment by alexwlchan** [comment]
Hmm. VersionAlreadyExistsError is already marked as Retryable, so what's going on here?

**Comment by alexwlchan** [comment]
And annoyingly the logs have now expired, and I didn't keep the rest of the error message.

**Comment by alexwlchan** [comment]
I think this was fixed in https://github.com/wellcometrust/storage-service/pull/411, and we haven't seen it since, so closing.
