### ISSUE TITLE
Run a single collection through Archivematica

### ISSUE THREAD

**Issue by alexwlchan** [wellcometrust/platform#4067]

**Comment by alexwlchan** [comment]
I’ve already moved Archivematica back to a single instance with a shared volume, so hopefully it'll be less flaky when services are split across hosts.

Now it's failing consistently at the "Store the AIP" step with the following error:

```
HTTPSConnectionPool(host='archivematica-storage-service-stage.wellcomecollection.org', port=443): Read timed out.Traceback (most recent call last):
  File "/src/MCPClient/lib/job.py", line 111, in JobContext
    yield
  File "/src/MCPClient/lib/clientScripts/store_aip.py", line 356, in call
    args.sip_type,
  File "/src/MCPClient/lib/clientScripts/store_aip.py", line 241, in store_aip
    related_package_uuid,
  File "/src/MCPClient/lib/clientScripts/store_aip.py", line 77, in _create_file
    agents=get_agents_from_db(uuid),
  File "/src/archivematicaCommon/lib/storageService.py", line 379, in create_file
    response = session.post(url, json=new_file, allow_redirects=False)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 581, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 686, in send
    r.content
  File "/usr/local/lib/python2.7/dist-packages/requests/models.py", line 828, in content
    self._content = b''.join(self.iter_content(CONTENT_CHUNK_SIZE)) or b''
  File "/usr/local/lib/python2.7/dist-packages/requests/models.py", line 757, in generate
    raise ConnectionError(e)
ConnectionError: HTTPSConnectionPool(host='archivematica-storage-service-stage.wellcomecollection.org', port=443): Read timed out.
```

**Comment by alexwlchan** [comment]
So we're POSTing to `/api/v2/file/async/`. What happens if we send a smaller bag?

**Comment by alexwlchan** [comment]
SABSO is 22MB, and worked.

**Comment by alexwlchan** [comment]
PPSML is 50MB, and worked. Err…

**Comment by alexwlchan** [comment]
This is working reliably enough now.
