### ISSUE TITLE
Bag too small/replica issue for "Send ingest request to archive service" step in Goobi

### ISSUE THREAD

**Issue by aray-wellcome** [wellcometrust/platform#4074]
b18664386 
b19122780
b18647807

The above bnumbers are stuck in "Send ingest request to archive service" because of the error:

> Unable to verify completeness of ingest, bNumber: b18647807. Could not obtain storage manifest from storage service, response code was 200, response body was: {"@context":"https://api.wellcomecollection.org/context.json","httpStatus":404,"description":"Storage manifest digitised/b18647807 not found","label":"Not Found","type":"Error"}

First ingest of bag: https://wellcome-ingest-inspector.glitch.me/ingests/09d5c04a-dce9-44a2-88a2-c3575b096300

Last ingest of bag: https://wellcome-ingest-inspector.glitch.me/ingests/b15240bb-dec4-4d01-bcd4-ad47e0a78a4e

**Comment by alexwlchan** [comment]
The replica aggregator is treating a `uk.ac.wellcome.storage.VersionAlreadyExistsError` as a deterministic error. I thought we'd fixed this, apparently not. Investigating…

**Comment by alexwlchan** [comment]
(Also, bumping straight onto the board because Ashley has hit this several times, and I'm waiting for stuff to upload to S3)

**Comment by alexwlchan** [comment]
Relevant stack trace:

```
15:02:52.027 [main-actor-system-akka.actor.default-dispatcher-2980] ERROR u.a.w.p.a.c.s.m.IngestStepWorker$$anon$1 - DeterministicFailure(java.lang.Error,Some(replicaPath=digitised/b18542335/v1, status=failed, ingestId=5caed46a-f765-46c9-a615-562272f75e26, duration=PT0.058479S, durationSeconds=0))
java.lang.Error: null
at uk.ac.wellcome.storage.VersionAlreadyExistsError$.apply$default$1(StorageError.scala:67)
at uk.ac.wellcome.storage.store.VersionedStore.put(VersionedStore.scala:100)
at uk.ac.wellcome.storage.store.VersionedStore.upsert(VersionedStore.scala:68)
at uk.ac.wellcome.platform.storage.replica_aggregator.services.ReplicaAggregator.aggregate(ReplicaAggregator.scala:21)
at uk.ac.wellcome.platform.storage.replica_aggregator.services.ReplicaAggregatorWorker.getKnownReplicas(ReplicaAggregatorWorker.scala:54)
at uk.ac.wellcome.platform.storage.replica_aggregator.services.ReplicaAggregatorWorker.processMessage(ReplicaAggregatorWorker.scala:71)
at uk.ac.wellcome.platform.storage.replica_aggregator.services.ReplicaAggregatorWorker.processMessage(ReplicaAggregatorWorker.scala:24)
at uk.ac.wellcome.platform.archive.common.storage.models.IngestStepWorker.process(IngestStepResult.scala:78)
at uk.ac.wellcome.platform.archive.common.storage.models.IngestStepWorker.process$(IngestStepResult.scala:77)
at uk.ac.wellcome.platform.storage.replica_aggregator.services.ReplicaAggregatorWorker.process(ReplicaAggregatorWorker.scala:24)
at uk.ac.wellcome.platform.archive.common.storage.models.IngestStepWorker$$anon$1$$anonfun$$lessinit$greater$1.apply(IngestStepResult.scala:82)
at uk.ac.wellcome.platform.archive.common.storage.models.IngestStepWorker$$anon$1$$anonfun$$lessinit$greater$1.apply(IngestStepResult.scala:82)
at uk.ac.wellcome.messaging.worker.steps.MessageProcessor.$anonfun$process$1(MessageProcessor.scala:18)
at scala.concurrent.Future.$anonfun$flatMap$1(Future.scala:303)
at scala.concurrent.impl.Promise.$anonfun$transformWith$1(Promise.scala:37)
at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:60)
at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:55)
at akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:91)
at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:81)
at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:91)
at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:40)
at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:44)
at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
```
