### ISSUE TITLE
Thread of unexplained Loris 500 errors

### ISSUE THREAD

**Issue by alexwlchan** [wellcometrust/platform#924]
This is a ticket for tracking any 500s we’ve seen from Loris that we haven’t fixed or explained.

We can split them off into their own tickets if/when we start working on them – for now, this is a place to dump errors that are transient/one-off.

**Comment by alexwlchan** [comment]
**ChunkedEncodingError: Connection reset by peer**

```
File "/usr/local/lib/python2.7/dist-packages/requests/models.py", line 748, in generate
  File "/usr/local/lib/python2.7/dist-packages/Loris-2.0.0-py2.7.egg/loris/webapp.py", line 445, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python2.7/dist-packages/Loris-2.0.0-py2.7.egg/loris/webapp.py", line 388, in wsgi_app
    response = self.route(request)
  File "/usr/local/lib/python2.7/dist-packages/Loris-2.0.0-py2.7.egg/loris/webapp.py", line 439, in route
    return self.get_img(request, ident, region, size, rotation, quality, fmt, base_uri)
  File "/usr/local/lib/python2.7/dist-packages/Loris-2.0.0-py2.7.egg/loris/webapp.py", line 572, in get_img
    info = self._get_info(ident, request, base_uri)[0]
File "/usr/local/lib/python2.7/dist-packages/Loris-2.0.0-py2.7.egg/loris/webapp.py", line 524, in _get_info
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/Loris-2.0.0-py2.7.egg/loris/resolver.py", line 396, in resolve
    cached_file_path = self.copy_to_cache(ident)
  File "/usr/local/lib/python2.7/dist-packages/Loris-2.0.0-py2.7.egg/loris/resolver.py", line 358, in copy_to_cache
    for chunk in response.iter_content(2048):
        info = self.resolver.resolve(self, ident, base_uri)
        raise ChunkedEncodingError(e)
requests.exceptions.ChunkedEncodingError: ("Connection broken: error(104, 'Connection reset by peer')", error(104, 'Connection reset by peer'))
```

https://eu-west-1.console.aws.amazon.com/cloudwatch/home?region=eu-west-1#logEventViewer:group=platform/loris;filter=%22HTTP/1.0%20500%22;start=2017-09-14T21:22:00Z;end=2017-09-14T21:32:00Z;

**Comment by alexwlchan** [comment]
**DecompressionBombWarning**

```
/usr/local/lib/python2.7/dist-packages/PIL/Image.py:2438: DecompressionBombWarning: Image size (116777610 pixels) exceeds limit of 89478485 pixels, could be decompression bomb DOS attack.
```

https://eu-west-1.console.aws.amazon.com/cloudwatch/home?region=eu-west-1#logEventViewer:group=platform/loris;filter=%22HTTP/1.0%20500%22;start=2017-09-14T13:20:00Z;end=2017-09-14T13:30:00Z;

**Comment by alexwlchan** [comment]
Another DecompressionBombWarning spotted, again unclear what it was trying to convert, but looks to be a different image:

```
/usr/local/lib/python2.7/dist-packages/PIL/Image.py:2496: DecompressionBombWarning: Image size (579836404 pixels) exceeds limit of 89478485 pixels, could be decompression bomb DOS attack.
```

https://eu-west-1.console.aws.amazon.com/cloudwatch/home?region=eu-west-1#logEventViewer:group=platform/loris;start=2017-10-12T22:18:00Z;end=2017-10-12T22:19:00Z

And an IOError "Cannot allocate memory":

```
cached_file_path = self.copy_to_cache(ident)
  File "/usr/local/lib/python2.7/dist-packages/Loris-2.0.0-py2.7.egg/loris/webapp.py", line 445, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python2.7/dist-packages/Loris-2.0.0-py2.7.egg/loris/webapp.py", line 388, in wsgi_app
    response = self.route(request)
  File "/usr/local/lib/python2.7/dist-packages/Loris-2.0.0-py2.7.egg/loris/webapp.py", line 439, in route
    return self.get_img(request, ident, region, size, rotation, quality, fmt, base_uri)
  File "/usr/local/lib/python2.7/dist-packages/Loris-2.0.0-py2.7.egg/loris/webapp.py", line 572, in get_img
    info = self._get_info(ident, request, base_uri)[0]
  File "/usr/local/lib/python2.7/dist-packages/Loris-2.0.0-py2.7.egg/loris/webapp.py", line 524, in _get_info
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/Loris-2.0.0-py2.7.egg/loris/resolver.py", line 399, in resolve
    info = self.resolver.resolve(self, ident, base_uri)
  File "/usr/local/lib/python2.7/dist-packages/Loris-2.0.0-py2.7.egg/loris/resolver.py", line 363, in copy_to_cache
    tmp_file.flush()
IOError: [Errno 12] Cannot allocate memory
```

But memory utilisation is low (<20%) for the whole night.

**Comment by alexwlchan** [comment]
Another DecompressionBombWarning:

```
/usr/local/lib/python2.7/dist-packages/PIL/Image.py:2496: DecompressionBombWarning: Image size (92999814 pixels) exceeds limit of 89478485 pixels, could be decompression bomb DOS attack.
```

https://eu-west-1.console.aws.amazon.com/cloudwatch/home?region=eu-west-1#logEventViewer:group=platform/loris;stream=06fab79e9d62223fc11d5b3b4daaf90595475919ec9164445c1f0373b9e3b43e;refid=33625983475496556701509278461862180196784998264012079108;reftime=1507841248180

**Comment by kenoir** [comment]
```
[pid: 87|app: 0|req: 53515/284392] 172.17.0.3 () {46 vars in 1209 bytes} [Sun Oct 29 20:41:59 2017] GET //prismic:7a5b0931-e8b0-4568-8f46-9cb3f430bdb9_map.png/full/282,/0/default.png => generated 55901 bytes in 85 msecs (HTTP/1.0 200) 7 headers in 436 bytes (236 switches on core 0)
Traceback (most recent call last):
File "/usr/local/lib/python2.7/dist-packages/Loris-2.0.0-py2.7.egg/loris/webapp.py", line 445, in __call__
[pid: 77|app: 0|req: 3934/284393] 172.17.0.3 () {46 vars in 1251 bytes} [Sun Oct 29 20:41:59 2017] GET //prismic:3231b5e5d3e8ffed4103365f92fc10cb3022b8c4_bodysquabbles-23-turds.jpg/full/30,/0/default.jpg => generated 1208 bytes in 196 msecs (HTTP/1.0 200) 7 headers in 458 bytes (9 switches on core 0)
return self.wsgi_app(environ, start_response)
File "/usr/local/lib/python2.7/dist-packages/Loris-2.0.0-py2.7.egg/loris/webapp.py", line 388, in wsgi_app
response = self.route(request)
File "/usr/local/lib/python2.7/dist-packages/Loris-2.0.0-py2.7.egg/loris/webapp.py", line 439, in route
return self.get_img(request, ident, region, size, rotation, quality, fmt, base_uri)
File "/usr/local/lib/python2.7/dist-packages/Loris-2.0.0-py2.7.egg/loris/webapp.py", line 572, in get_img
File "/usr/local/lib/python2.7/dist-packages/Loris-2.0.0-py2.7.egg/loris/resolver.py", line 399, in resolve
info = self._get_info(ident, request, base_uri)[0]
info = self.resolver.resolve(self, ident, base_uri)
File "/usr/local/lib/python2.7/dist-packages/Loris-2.0.0-py2.7.egg/loris/webapp.py", line 524, in _get_info
cached_file_path = self.copy_to_cache(ident)
File "/usr/local/lib/python2.7/dist-packages/Loris-2.0.0-py2.7.egg/loris/resolver.py", line 361, in copy_to_cache
for chunk in response.iter_content(2048):
File "/usr/local/lib/python2.7/dist-packages/requests/models.py", line 748, in generate
raise ChunkedEncodingError(e)
requests.exceptions.ChunkedEncodingError: ("Connection broken: error(104, 'Connection reset by peer')", error(104, 'Connection reset by peer'))
```

Seen a couple of these, i'm not sure if this is down to Loris not handling broken connections well?

Do you reckon this is a Loris bug @alexwlchan?

**Comment by pollecuttn** [comment]
30/10/17:
5:42 PM] 
loris-alb-target-500-errors
----------------
The ALB spotted a 500 error in Loris at 17:40:00 on 30 Oct 2017.

CloudWatch messages
----------------
GET /s3:L0072000/L0072887.jpg/full/282,/0/default.jpg => generated 0 bytes in 271 msecs (HTTP/1.0 500)

----------------
http://amzn.to/2lts1nv

**Comment by alexwlchan** [comment]
The ALB spotted a 500 error in Loris at 09:30:00 on 06 Nov 2017.

```
requests.exceptions.ChunkedEncodingError: ("Connection broken: error(104, 'Connection reset by peer')", error(104, 'Connection reset by peer'))
GET /s3:N0037000/N0037641.jpg/full/180,/0/default.jpg => generated 0 bytes in 284 msecs (HTTP/1.0 500)
```

**Comment by alexwlchan** [comment]
And again:

The ALB spotted a 500 error in Loris at 10:17:00 on 04 Nov 2017.

```
requests.exceptions.ChunkedEncodingError: ("Connection broken: error(104, 'Connection reset by peer')", error(104, 'Connection reset by peer'))
GET /s3:M0013000/M0013206.jpg/full/282,/0/default.jpg => generated 0 bytes in 324 msecs (HTTP/1.0 500)
```
